-- Query FOS catch from the merged catch table GF_D_OFFICIAL_FE_CATCH
SELECT * FROM (
SELECT 
  (CASE
    WHEN FC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') THEN 1
    WHEN FC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') THEN 2
    WHEN FC.FISHERY_SECTOR IN ('SABLEFISH') THEN 3
    WHEN FC.FISHERY_SECTOR IN ('LINGCOD','SPINY DOGFISH') THEN 4
    WHEN FC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') THEN 5
    ELSE 0 END) AS \"fid\",
  FC.FISHERY_SECTOR AS \"sector\",
  CASE
    WHEN FC.GEAR IN ('TRAWL') AND FC.GEAR_SUBTYPE NOT IN ('MIDWATER TRAWL') THEN 1
    WHEN FC.GEAR IN ('TRAP') THEN 2
    WHEN FC.GEAR IN ('TRAWL') AND FC.GEAR_SUBTYPE IN ('MIDWATER TRAWL') THEN 3
    WHEN FC.GEAR IN ('HOOK AND LINE') THEN 4
    WHEN FC.GEAR IN ('LONGLINE') THEN 5
    WHEN FC.GEAR IN ('LONGLINE OR HOOK AND LINE','TRAP OR LONGLINE OR HOOK AND LINE') THEN 8
    ELSE 0 END AS \"gear\",
  NVL(FC.DATA_SOURCE_CODE,0) AS \"log\",
  TO_DATE(TO_CHAR(FC.BEST_DATE,'YYYY-MM-DD'),'YYYY-MM-DD') as \"date\",
  NVL(FC.MAJOR_STAT_AREA_CODE,'0') AS \"major\",
  NVL(FC.MINOR_STAT_AREA_CODE,'0') AS \"minor\",
  CC.landed AS \"landed\",
  CC.released + CC.liced + CC.bait AS \"discard\",
  CC.POP, CC.ORF, CC.TAR
FROM 
  GFFOS.GF_D_OFFICIAL_FE_CATCH FC INNER JOIN
  (SELECT
    OC.TRIP_ID,
    OC.FISHING_EVENT_ID,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@sppcode) THEN NVL(OC.LANDED_ROUND_KG,0)
      ELSE 0 END) AS landed,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@sppcode) THEN
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0)
      ELSE 0 END) AS released,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@sppcode) THEN
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT
      ELSE 0 END) AS liced,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@sppcode) THEN
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT
      ELSE 0 END) AS bait,
    SUM(CASE
      WHEN OC.SPECIES_CODE IN ('396') THEN NVL(OC.LANDED_ROUND_KG,0)
      ELSE 0 END) AS POP,
    SUM(CASE  -- all rockfish other than POP
      WHEN OC.SPECIES_CODE IN (@orfcode) THEN NVL(OC.LANDED_ROUND_KG,0)
      ELSE 0 END) AS ORF,
    SUM(CASE  -- target landings reference for discard calculations
      WHEN OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND OC.SPECIES_CODE IN (@trfcode)
        THEN NVL(OC.LANDED_ROUND_KG,0)
      WHEN OC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') AND OC.SPECIES_CODE IN ('614')
        THEN NVL(OC.LANDED_ROUND_KG,0)
      WHEN OC.FISHERY_SECTOR IN ('SABLEFISH') AND OC.SPECIES_CODE IN ('454','455')
        THEN NVL(OC.LANDED_ROUND_KG,0)
      WHEN OC.FISHERY_SECTOR IN ('SPINY DOGFISH') AND OC.SPECIES_CODE IN ('042','044')
        THEN NVL(OC.LANDED_ROUND_KG,0)
      WHEN OC.FISHERY_SECTOR IN ('LINGCOD') AND OC.SPECIES_CODE IN ('467')
        THEN NVL(OC.LANDED_ROUND_KG,0)
      WHEN OC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') AND OC.SPECIES_CODE IN ('424','407','431','433','442')
        THEN NVL(OC.LANDED_ROUND_KG,0)
      ELSE 0 END) AS TAR
  FROM GFFOS.GF_D_OFFICIAL_FE_CATCH OC INNER JOIN

-- FISH WEIGHTS FW
  GFFOS.MEAN_SPECIES_WEIGHT_VW FW ON
    OC.SPECIES_CODE = FW.SPP
  GROUP BY OC.TRIP_ID, OC.FISHING_EVENT_ID ) CC ON
    FC.TRIP_ID = CC.TRIP_ID AND
    FC.FISHING_EVENT_ID = CC.FISHING_EVENT_ID 

WHERE 
  FC.SPECIES_CODE IN (@sppcode) AND 
  (FC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') OR 
  (FC.FISHERY_SECTOR NOT IN ('GROUNDFISH TRAWL') AND NVL(FC.DATA_SOURCE_CODE,0) NOT IN (106,107)))

ORDER BY FC.TRIP_ID, FC.FISHING_EVENT_ID
) ORF
WHERE
  ORF.\"landed\">0 OR ORF.\"discard\">0 OR ORF.POP>0 OR ORF.ORF>0 OR ORF.TAR>0
;
-- getData("fos_vcatORF.sql","GFFOS",strSpp="415",server="GFSH",type="ORA",path=.getSpath(),trusted=F,uid=Sys.info()["user"],pwd=)
-- getData("fos_vcatORF.sql","GFFOS",strSpp="415",server="GFSH",type="ORA",trusted=F,uid=Sys.info()["user"],pwd=)

