-- Get survey catch from GFBioSQL for clara analysis (2013-01-21)
SET NOCOUNT ON

SELECT
  C.SPECIES_CODE,
  Avg(C.CATCH_WEIGHT) AS mnwt, 
  Avg(C.CATCH_COUNT) AS mnct, 
  Count(C.CATCH_WEIGHT) AS n, 
  Avg(C.CATCH_WEIGHT/C.CATCH_COUNT) AS sppwt
INTO #SPP_WEIGHT
FROM B03_CATCH C
WHERE
--  C.SPECIES_CODE IN (@sppcode) AND 
  C.CATCH_WEIGHT > 0 AND
  C.CATCH_COUNT > 1
GROUP BY 
  C.SPECIES_CODE

SELECT
  FE.TRIP_ID, FE.FISHING_EVENT_ID,
  COALESCE(FE.FE_MODAL_BOTTOM_DEPTH, FE.FE_MODAL_GEAR_DEPTH, FE.FE_MODAL_CAPTURE_DEPTH, FE.FE_MODAL_TARGET_DEPTH, 0) AS Zmod,
  COALESCE(FE.FE_BEGINNING_BOTTOM_DEPTH, FE.FE_BEGINNING_GEAR_DEPTH, FE.FE_BEGIN_CAPTURE_DEPTH, FE.FE_BEGIN_TARGET_DEPTH, 0) AS Zbeg,
  COALESCE(FE.FE_END_BOTTOM_DEPTH, FE.FE_END_GEAR_DEPTH, FE.FE_END_CAPTURE_DEPTH, FE.FE_END_TARGET_DEPTH, 0) AS Zend,
  COALESCE(FE.FE_MIN_BOTTOM_DEPTH, FE.FE_MIN_GEAR_DEPTH, FE.FE_MIN_CAPTURE_DEPTH, FE.FE_MIN_TARGET_DEPTH, 0) AS Zmin,
  COALESCE(FE.FE_MAX_BOTTOM_DEPTH, FE.FE_MAX_GEAR_DEPTH, FE.FE_MAX_CAPTURE_DEPTH, FE.FE_MAX_TARGET_DEPTH, 0) AS Zmax
INTO #DEPTHS
FROM
  B02_FISHING_EVENT FE

SELECT
  FE.TRIP_ID,
  FE.FISHING_EVENT_ID,
  COALESCE(-(FE.FE_START_LONGITUDE_DEGREE + (FE.FE_START_LONGITUDE_MINUTE/60.)),
    -(FE.FE_END_LONGITUDE_DEGREE + (FE.FE_END_LONGITUDE_MINUTE/60.)),0) AS LON,
  COALESCE(FE.FE_START_LATTITUDE_DEGREE + (FE.FE_START_LATTITUDE_MINUTE/60.),
    FE.FE_END_LATTITUDE_DEGREE + (FE.FE_END_LATTITUDE_MINUTE/60.),0) AS LAT,
  CASE 
    WHEN D.Zmod > 0 THEN D.Zmod
    WHEN D.Zbeg > 0 AND D.Zend > 0 THEN (D.Zbeg + D.Zend) / 2.
    WHEN D.Zbeg > 0 THEN D.Zbeg
    WHEN D.Zend > 0 THEN D.Zend
    WHEN D.Zmin > 0 AND D.Zmax > 0 THEN (D.Zmin + D.Zmax) / 2.
    WHEN D.Zmin > 0 THEN D.Zmin
    WHEN D.Zmax > 0 THEN D.Zmax
    ELSE 0 END AS DEP
INTO #FE_SIMPLE
FROM
  B02_FISHING_EVENT FE INNER JOIN
  #DEPTHS D ON
  FE.TRIP_ID = D.TRIP_ID AND
  FE.FISHING_EVENT_ID = D.FISHING_EVENT_ID
 
SELECT --TOP 25
  S.SURVEY_SERIES_ID AS SSID,
  S.SURVEY_ID AS SID,
  T.TRIP_ID AS TID,
  FE.FISHING_EVENT_ID AS FEID,
  FE.LON AS X,
  FE.LAT AS Y,
  FE.DEP AS Z,
  --C.CATCH_ID AS CID,
  C.SPECIES_CODE AS spp,
  COALESCE(C.CATCH_WEIGHT, C.CATCH_COUNT * W.sppwt, 0) AS catKg
  --C.CATCH_WEIGHT AS catKg
FROM
  SURVEY S INNER JOIN 
  TRIP_SURVEY TS INNER JOIN 
  B01_TRIP T INNER JOIN
  #FE_SIMPLE FE INNER JOIN 
  B02L3_Link_Fishing_Event_Catch B2B3 INNER JOIN 
  B03_CATCH C LEFT OUTER JOIN
  #SPP_WEIGHT W ON
    W.SPECIES_CODE = C.SPECIES_CODE ON
    C.CATCH_ID = B2B3.CATCH_ID ON
    B2B3.TRIP_ID = FE.TRIP_ID AND
    B2B3.FISHING_EVENT_ID = FE.FISHING_EVENT_ID ON
    FE.TRIP_ID = T.TRIP_ID ON
    T.TRIP_ID = TS.TRIP_ID ON
    S.SURVEY_ID = TS.SURVEY_ID
WHERE 
  S.SURVEY_SERIES_ID IN (@survserid) AND
  C.SPECIES_CODE IN (@invcode)

-- getData("gfb_clara_survey.sql","GFBioSQL",strSpp="000")

