-- Get Norm's bootstrap results
SET NOCOUNT ON

SELECT
  S.SURVEY_SERIES_ID AS serID,
  TS.SURVEY_ID AS survID,
  BH.BOOT_ID AS bootID,
  T.TRIP_START_DATE AS [date],
  Year(T.TRIP_START_DATE) AS [year],
  BH.DEFAULT_DOORSPREAD AS defDoor,
  BH.DEFAULT_SPEED AS defSpeed,
  BH.RUN_DESC AS runDesc,
  BD.BIOMASS AS biomass,
  BD.BOOT_MEAN AS bootMean,
  BD.BOOT_MEDIAN AS bootMedian,
  BD.BOOT_LOWER_CI AS bootLoCI,
  BD.BOOT_UPPER_CI AS bootHiCI,
  BD.BOOT_RE AS bootRE,
  BD.CATCH_WEIGHT AS catchWt,
  BD.NUM_SETS AS numSets,
  BD.NUM_POS_SETS AS numPosSets
FROM 
  B01_TRIP T INNER JOIN 
  TRIP_SURVEY TS ON 
    T.TRIP_ID = TS.TRIP_ID INNER JOIN
  SURVEY S ON
    TS.SURVEY_ID = S.SURVEY_ID INNER JOIN
  BOOT_HEADER BH ON 
    TS.SURVEY_ID = BH.SURVEY_ID INNER JOIN
  BOOT_DETAIL BD ON 
    BH.BOOT_ID = BD.BOOT_ID
WHERE 
  BD.SPECIES_CODE IN (@sppcode)
ORDER BY
  S.SURVEY_SERIES_ID, TS.SURVEY_ID, BH.BOOT_ID

-- getData("gfb_boot.sql","GFBioSQL",strSpp="451")

