SET NOCOUNT ON

SELECT 
  SA.TRIP_ID AS TID, 
  SA.FISHING_EVENT_ID AS FID, 
  SA.SAMPLE_ID AS SID, 
  SP.SPECIMEN_ID AS SPID, 
  SA.TRIP_SUB_TYPE_CODE AS ttype, 
  SA.SAMPLE_TYPE_CODE AS stype, 
  SP.SPECIMEN_SEX_CODE AS sex, 
  SP.MATURITY_CODE AS mat, 
  SP.SPECIMEN_AGE AS age, 
  SP.AGEING_METHOD_CODE AS ameth, 
  SP.Best_Length AS len, 
  SP.Round_Weight AS wt, 
  Year(SA.SAMPLE_DATE) AS [year], 
  SA.Best_Depth AS fdep, 
  SA.GEAR_CODE AS gear, 
  SA.MAJOR_STAT_AREA_CODE AS major, 
  SA.MINOR_STAT_AREA_CODE AS minor, 
  SA.LOCALITY_CODE AS locality, 
  SA.BLOCK_DESIGNATION AS block 
FROM 
  B21_Samples SA INNER JOIN 
  B22_Specimens SP ON 
  SA.SAMPLE_ID = SP.SAMPLE_ID 
WHERE 
  SP.SPECIES_CODE=@sppcode AND 
  (SA.BLOCK_DESIGNATION='TASU' OR SA.BLOCK_DESIGNATION='FLAMINGO' OR 
   SA.BLOCK_DESIGNATION='TRIANGLE' OR SA.BLOCK_DESIGNATION='BROOKS')

