SET NOCOUNT ON

SELECT 
  CC.fyear, 
  SUM(CASE RM WHEN '3C' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '3C', 
  SUM(CASE RM WHEN '3D' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '3D', 
  SUM(CASE RM WHEN '4B' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '4B', 
  SUM(CASE RM WHEN '5A' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '5A', 
  SUM(CASE RM WHEN '5B' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '5B', 
  SUM(CASE RM WHEN '5C' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '5C', 
  SUM(CASE RM WHEN '5D' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '5D', 
  SUM(CASE RM WHEN '5E' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS '5E', 
  SUM(CASE RM WHEN 'UNK' THEN (CC.LANDED + CC.DISCARDED) END) / 1000 AS 'UNK' 
FROM 
  (SELECT
    cast(CASE WHEN E.Fishing_Year = '97' THEN '19967' 
      WHEN (E.Fishing_Year IS NULL) 
      THEN '9999' ELSE E.Fishing_Year END AS VARCHAR) AS fyear, 
    E.OBFL_MAJOR_STAT_AREA_CDE, 
    C.SPECIES_CODE, 
    C.LANDED, C.DISCARDED, 
    RM = CASE E.OBFL_MAJOR_STAT_AREA_CDE 
      WHEN 1 THEN '4B' 
      WHEN 3 THEN '3C' 
      WHEN 4 THEN '3D' 
      WHEN 5 THEN '5A' 
      WHEN 6 THEN '5B' 
      WHEN 7 THEN '5C' 
      WHEN 8 THEN '5D' 
      WHEN 9 THEN '5E' 
      ELSE 'UNK' END 
  FROM 
    B3_Fishing_Events E RIGHT OUTER JOIN 
    D_Merged_Catches C ON 
    E.OBFL_HAIL_IN_NO = C.HAIL_IN_NO AND 
    E.OBFL_SET_NO = C.SET_NO 
  WHERE 
    C.SPECIES_CODE = @sppcode) AS CC
GROUP BY fyear 
ORDER BY fyear;
