-- Query FOS catch from the merged catch table GF_D_OFFICIAL_FE_CATCH
-- Query species catch from GFFOS on SVBCPBSGFIIS
-- Last modified: 2016-04-12 (RH)
SET NOCOUNT ON 

-- Mean species weight calculated using `gfb_mean_weight.sql', which emulates PJS algorithm for GFBIO data
@INSERT('meanSppWt.sql')  -- getData now inserts the specified SQL file assuming it's on the `path' specified in `getData'
-- Usage: SELECT FW.MEAN_WEIGHT FROM @MEAN_WEIGHT FW WHERE FW.SPECIES_CODE IN('222')

-- Gather catch of RRF, POP, ORF, TAR
SELECT -- TOP 20
  OC.TRIP_ID,
  OC.FISHING_EVENT_ID,
  --ISNULL(L.LOCALITY_DESCRIPTION,'MOOSE COUNTY') AS LOCAL_NAME,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN ISNULL(OC.LANDED_ROUND_KG,0)
    ELSE 0 END) AS landed,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (ISNULL(OC.SUBLEGAL_RELEASED_COUNT,0) + ISNULL(OC.LEGAL_RELEASED_COUNT,0)) * ISNULL(FW.MNWT,1), 0)
    ELSE 0 END) AS released,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      (ISNULL(OC.SUBLEGAL_LICED_COUNT,0) + ISNULL(OC.LEGAL_LICED_COUNT,0)) * ISNULL(FW.MNWT,1)
    ELSE 0 END) AS liced,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      (ISNULL(OC.SUBLEGAL_BAIT_COUNT,0) + ISNULL(OC.LEGAL_BAIT_COUNT,0)) * ISNULL(FW.MNWT,1)
    ELSE 0 END) AS bait,
  SUM(CASE
    WHEN OC.SPECIES_CODE IN ('396') THEN ISNULL(OC.LANDED_ROUND_KG,0)
    ELSE 0 END) AS POP,
  SUM(CASE  -- all rockfish other than POP
    WHEN OC.SPECIES_CODE IN (@orfcode) THEN ISNULL(OC.LANDED_ROUND_KG,0)
    ELSE 0 END) AS ORF,
  SUM(CASE  -- target landings reference for discard calculations
    WHEN OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND OC.SPECIES_CODE IN (@trfcode)
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    WHEN OC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') AND OC.SPECIES_CODE IN ('614')
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    WHEN OC.FISHERY_SECTOR IN ('SABLEFISH') AND OC.SPECIES_CODE IN ('454','455')
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    WHEN OC.FISHERY_SECTOR IN ('SPINY DOGFISH') AND OC.SPECIES_CODE IN ('042','044')
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    WHEN OC.FISHERY_SECTOR IN ('LINGCOD') AND OC.SPECIES_CODE IN ('467')
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    WHEN OC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') AND OC.SPECIES_CODE IN ('424','407','431','433','442')
      THEN ISNULL(OC.LANDED_ROUND_KG,0)
    ELSE 0 END) AS TAR
INTO #CATCH_CORE
FROM 
  --LOCALITY L RIGHT OUTER JOIN
  (GF_D_OFFICIAL_FE_CATCH OC LEFT OUTER JOIN
  @MEAN_WEIGHT FW ON
    OC.SPECIES_CODE = FW.SPECIES_CODE) --ON
  --L.MAJOR_STAT_AREA_CODE = OC.MAJOR_STAT_AREA_CODE AND
  --L.MINOR_STAT_AREA_CODE = OC.MINOR_STAT_AREA_CODE AND
  --L.LOCALITY_CODE = OC.LOCALITY_CODE
--WHERE ISNULL(L.LOCALITY_DESCRIPTION,'MOOSE COUNTY') NOT LIKE '%MOUNT%'
GROUP BY OC.TRIP_ID, OC.FISHING_EVENT_ID--,
  --ISNULL(L.LOCALITY_DESCRIPTION,'MOOSE COUNTY')

-- Combine event information with catch
SELECT
  (CASE
    WHEN FC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') THEN 1
    WHEN FC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') THEN 2
    WHEN FC.FISHERY_SECTOR IN ('SABLEFISH') THEN 3
    WHEN FC.FISHERY_SECTOR IN ('LINGCOD','SPINY DOGFISH') THEN 4
    WHEN FC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') THEN 5
    ELSE 0 END) AS \"fid\",
  FC.FISHERY_SECTOR AS \"sector\",
  CASE
    WHEN FC.GEAR IN ('TRAWL') AND FC.GEAR_SUBTYPE NOT IN ('MIDWATER TRAWL') THEN 1
    WHEN FC.GEAR IN ('TRAP') THEN 2
    WHEN FC.GEAR IN ('TRAWL') AND FC.GEAR_SUBTYPE IN ('MIDWATER TRAWL') THEN 3
    WHEN FC.GEAR IN ('HOOK AND LINE') THEN 4
    WHEN FC.GEAR IN ('LONGLINE') THEN 5
    WHEN FC.GEAR IN ('LONGLINE OR HOOK AND LINE','TRAP OR LONGLINE OR HOOK AND LINE') THEN 8
    ELSE 0 END AS \"gear\",
  ISNULL(FC.DATA_SOURCE_CODE,0) AS \"log\",
  --TO_DATE(TO_CHAR(FC.BEST_DATE,'YYYY-MM-DD'),'YYYY-MM-DD') as \"date\",
  CONVERT(VARCHAR(10),FC.BEST_DATE,20) as \"date\",
  ISNULL(FC.MAJOR_STAT_AREA_CODE,'0') AS \"major\",
  ISNULL(FC.MINOR_STAT_AREA_CODE,'0') AS \"minor\",
  ISNULL(FC.LOCALITY_CODE,'0') AS \"locality\",
  --CC.LOCAL_NAME, -- for debugging locality names
  CC.landed AS \"landed\",
  CC.released + CC.liced + CC.bait AS \"discard\",
  CC.POP, CC.ORF, CC.TAR
INTO #CATCH_EVENTS
FROM 
  GF_D_OFFICIAL_FE_CATCH FC INNER JOIN
  #CATCH_CORE CC ON
    FC.TRIP_ID = CC.TRIP_ID AND
    FC.FISHING_EVENT_ID = CC.FISHING_EVENT_ID 
WHERE 
  FC.SPECIES_CODE IN (@sppcode) AND 
  (FC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') OR 
  (FC.FISHERY_SECTOR NOT IN ('GROUNDFISH TRAWL') AND ISNULL(FC.DATA_SOURCE_CODE,0) NOT IN (106,107)))
ORDER BY FC.TRIP_ID, FC.FISHING_EVENT_ID

SELECT * 
FROM #CATCH_EVENTS ORF
WHERE
  ORF.\"landed\">0 OR ORF.\"discard\">0 OR ORF.POP>0 OR ORF.ORF>0 OR ORF.TAR>0

-- getData("fos_vcatORF.sql","GFFOS",strSpp="442")
-- qu("fos_vcatORF.sql",dbName="GFFOS",strSpp="442")



