-- Query to determine catch weight of RRF compared to TRF for statement in TOR (started with WWR 2019)
SELECT --TOP 100
  MC.LONGITUDE AS X,
  MC.LATITUDE AS Y,
  MC.BEST_DEPTH AS Z,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('435') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as BOR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('396') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as POP,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('418') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as YTR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('440') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as YMR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('405') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as SGR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('439') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as RSR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('437') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as CAR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('394') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as RER,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('450') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as SCR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('417') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as WWR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('401') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)
    ELSE 0 END) as RBR
FROM 
  GF_MERGED_CATCH MC
WHERE
  Year(MC.BEST_DATE) BETWEEN 1996 AND 2019
  AND MC.LONGITUDE IS NOT NULL
  AND MC.LATITUDE IS NOT NULL
  AND MC.BEST_DEPTH IS NOT NULL
  AND MC.MAJOR_STAT_AREA_CODE IN ('03','04','05','06','07','08','09')
  --AND MC.GEAR IN ('MIDWATER TRAWL')
  AND MC.GEAR IN ('BOTTOM TRAWL', 'UNKNOWN TRAWL')
  --AND MC.GEAR IN ('BOTTOM TRAWL', 'MIDWATER TRAWL', 'UNKNOWN TRAWL')
GROUP BY
  MC.LONGITUDE,
  MC.LATITUDE,
  MC.BEST_DEPTH

--qu("fos_bor_clara.sql", dbName="GFFOS", strSpp="999")
