-- Query to determine catch weight of RRF compared to TRF for statement in TOR (started with WWR 2019)
SELECT --TOP 100
  MC.LONGITUDE AS X,
  MC.LATITUDE AS Y,
  MC.BEST_DEPTH AS Z,
  CONVERT(SMALLDATETIME,CONVERT(char(10),MC.BEST_DATE, 20)) AS 'date',
  CONVERT(INTEGER, ISNULL(MC.MAJOR_STAT_AREA_CODE,'00')) AS major,
  CONVERT(INTEGER, ISNULL(MC.MINOR_STAT_AREA_CODE,'00')) AS minor,
  ISNULL(MC.LOCALITY_CODE,0) AS locality,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('394') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RER|BSR|REBS Rougheye/Blackspotted Rockfish
    ELSE 0 END) as RER,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('396') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- POP Pacific Ocean Perch
    ELSE 0 END) as POP,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('400') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- AUR Aurora rockfish
    ELSE 0 END) as AUR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('401') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RBR Redbanded rockfish
    ELSE 0 END) as RBR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('403') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SKR Shortraker rockfish
    ELSE 0 END) as SKR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('405') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SGR Silvergray rockfish
    ELSE 0 END) as SGR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('407') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- CPR Copper rockfish
    ELSE 0 END) as CPR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('409') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- DKR Dusky rockfish
    ELSE 0 END) as DKR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('410') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- DBR Darkblotched rockfish
    ELSE 0 END) as DBR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('412') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SNR Splitnose rockfish
    ELSE 0 END) as SNR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('414') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- GSR Greenstriped rockfish
    ELSE 0 END) as GSR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('417') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- WWR Widow rockfish
    ELSE 0 END) as WWR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('418') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YTR Yellowtail rockfish
    ELSE 0 END) as YTR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('420') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- CHI Chilipepper
    ELSE 0 END) as CHI,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('421') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RTR Rosethorn rockfish
    ELSE 0 END) as RTR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('423') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SBR Shortbelly rockfish
    ELSE 0 END) as SBR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('424') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- QBR Quillback rockfish
    ELSE 0 END) as QBR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('425') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- BSR Blackspotted rockfish
    ELSE 0 END) as BSR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('426') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- BKR Black rockfish
    ELSE 0 END) as BKR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('428') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- VMR Vermilion rockfish
    ELSE 0 END) as VMR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('431') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- CHR China rockfish
    ELSE 0 END) as CHR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('433') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- TIR Tiger Rockfish
    ELSE 0 END) as TIR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('435') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- BOR Bocaccio
    ELSE 0 END) as BOR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('437') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- CAR Canary Rockfish
    ELSE 0 END) as CAR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('439') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RSR Redstripe Rockfish
    ELSE 0 END) as RSR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('440') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YMR Yellowmouth Rockfish
    ELSE 0 END) as YMR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('442') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YYR Yelloweye Rockfish
    ELSE 0 END) as YYR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('443') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- BAR Bank Rockfish
    ELSE 0 END) as BAR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('446') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- HQR Harlequin rockfish
    ELSE 0 END) as HQR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('450') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SCR Sharpchin rockfish
    ELSE 0 END) as SCR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('451') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SST Shortspine Thornyhead
    ELSE 0 END) as SST,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('453') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- LST Longspine Thornyhead
    ELSE 0 END) as LST
FROM 
  GF_MERGED_CATCH MC
WHERE
  Year(MC.BEST_DATE) BETWEEN 1996 AND 2021
  AND MC.LONGITUDE IS NOT NULL
  AND MC.LATITUDE IS NOT NULL
  AND MC.BEST_DEPTH IS NOT NULL
  AND MC.MAJOR_STAT_AREA_CODE IN ('03','04','05','06','07','08','09')
  --AND MC.GEAR IN ('MIDWATER TRAWL')
  AND MC.GEAR IN ('BOTTOM TRAWL', 'UNKNOWN TRAWL')
  --AND MC.GEAR IN ('BOTTOM TRAWL', 'MIDWATER TRAWL', 'UNKNOWN TRAWL')
GROUP BY
  MC.LONGITUDE,
  MC.LATITUDE,
  MC.BEST_DEPTH,
  CONVERT(SMALLDATETIME,CONVERT(char(10),MC.BEST_DATE, 20)),
  CONVERT(INTEGER, ISNULL(MC.MAJOR_STAT_AREA_CODE,'00')),
  CONVERT(INTEGER, ISNULL(MC.MINOR_STAT_AREA_CODE,'00')),
  ISNULL(MC.LOCALITY_CODE,0)

--qu("fos_clara_rf_bt.sql", dbName="GFFOS", strSpp="999")
