-- GFFOS query for fish group catches (2010-10-12)
-- Query FOS catch from the merged catch table GF_D_OFFICIAL_FE_CATCH
SELECT 
  NVL(TO_NUMBER(TO_CHAR(PP.BIG_DATE,'YYYY')),9999) AS \"year\",
  SUM(PP.POP)/1000. AS POP,
  SUM(PP.ROCKFISH)/1000. AS \"rockfish\",
  SUM(PP.TURBOT)/1000. AS \"turbot\",
  SUM(PP.FLATFISH)/1000. AS \"flatfish\",
  SUM(PP.HAKE)/1000. AS \"hake\",
  SUM(PP.SHARKS)/1000. AS \"sharks\",
  SUM(PP.ALLFISH-PP.POP-PP.ROCKFISH-PP.TURBOT-PP.FLATFISH-PP.HAKE-PP.SHARKS)/1000. AS \"other\"
FROM 
  (SELECT * FROM 
  (SELECT
    OC.TRIP_ID,
    OC.FISHING_EVENT_ID,
    TO_DATE(TO_CHAR(COALESCE(OC.BEST_DATE,ED.EVENT_DATE,TD.TRIP_DATE),'YYYY-MM-DD'),'YYYY-MM-DD') AS BIG_DATE,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN ('396') THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS POP,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@orfcode) THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS ROCKFISH,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN ('602') THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS TURBOT,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@offcode) THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS FLATFISH,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN ('224','225') THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS HAKE,
    Sum(CASE
      WHEN OC.SPECIES_CODE IN (@ssscode) THEN NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ELSE 0 END) AS SHARKS,
    Sum(NVL(OC.LANDED_ROUND_KG,0) +
        COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
        (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
        (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
        (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT                -- bait
      ) AS ALLFISH

  FROM 
    (GFFOS.GF_D_OFFICIAL_FE_CATCH OC 
    INNER JOIN GFFOS.MEAN_SPECIES_WEIGHT_VW FW ON -- FISH WEIGHTS FW
      OC.SPECIES_CODE = FW.SPP)

    LEFT OUTER JOIN (SELECT  -- TRIP DATA
      T1.TRIP_ID,
      MAX(TO_DATE(TO_CHAR(COALESCE(E1.START_DATE, E1.END_DATE,T1.TRIP_START_DATE,T1.TRIP_END_DATE),'YYYY-MM-DD'),'YYYY-MM-DD')) AS TRIP_DATE,
      MAX(NVL(A1.MAJOR_STAT_AREA_CODE,'00')) AS TRIP_MAJOR,
      MAX(COALESCE(E1.START_DEPTH_FM,END_DEPTH_FM,MID_DEPTH_FM,0)) AS TRIP_DEPTH
    FROM
      (@table.GF_TRIP T1 RIGHT OUTER JOIN
      @table.GF_FISHING_EVENT E1 ON
        T1.TRIP_ID = E1.TRIP_ID) LEFT OUTER JOIN
      @table.GF_FE_DERIVED_AREA A1 ON
        E1.FISHING_EVENT_ID = A1.FISHING_EVENT_ID
    GROUP BY  T1.TRIP_ID  ) TD ON
      OC.TRIP_ID = TD.TRIP_ID

    LEFT OUTER JOIN (SELECT  -- EVENT DATA
      E2.TRIP_ID, E2.FISHING_EVENT_ID,
      --E2.FISHERY_SECTOR, E2.GEAR_SUBTYPE,
      TO_DATE(TO_CHAR(COALESCE(E2.START_DATE, E2.END_DATE,T2.TRIP_START_DATE,T2.TRIP_END_DATE),'YYYY-MM-DD'),'YYYY-MM-DD') AS EVENT_DATE,
      NVL(A2.MAJOR_STAT_AREA_CODE,'00') AS EVENT_MAJOR,
      COALESCE(E2.START_DEPTH_FM,END_DEPTH_FM,MID_DEPTH_FM,0) AS EVENT_DEPTH
    FROM
      (@table.GF_TRIP T2 RIGHT OUTER JOIN
      @table.GF_FISHING_EVENT E2 ON
        T2.TRIP_ID = E2.TRIP_ID) LEFT OUTER JOIN
      @table.GF_FE_DERIVED_AREA A2 ON
        E2.FISHING_EVENT_ID = A2.FISHING_EVENT_ID ) ED ON
      OC.TRIP_ID = ED.TRIP_ID AND
      OC.FISHING_EVENT_ID = ED.FISHING_EVENT_ID

  WHERE 
    OC.SPECIES_CODE IN (@alfcode) AND
    OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND
    COALESCE(OC.MAJOR_STAT_AREA_CODE,ED.EVENT_MAJOR,TD.TRIP_MAJOR,'00') IN (@major) AND
    COALESCE(OC.BEST_DEPTH_FM,OC.START_DEPTH_FM,ED.EVENT_DEPTH,TD.TRIP_DEPTH,0)*1.8288 BETWEEN @mindep AND @maxdep AND
    (CASE WHEN
      (OC.GEAR_SUBTYPE IN ('HARD BOTTOM TRAWL','SOFT BOTTOM TRAWL') OR   -- bottom
      (OC.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
      OC.TRIP_CATEGORY NOT IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
      THEN 1
    WHEN
      (OC.GEAR_SUBTYPE IN ('MIDWATER TRAWL') OR   -- midwater
      (OC.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
      OC.TRIP_CATEGORY IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
    THEN 3 ELSE 0 END) IN (@dummy) 

  GROUP BY 
    OC.TRIP_ID, OC.FISHING_EVENT_ID,
    TO_DATE(TO_CHAR(COALESCE(OC.BEST_DATE,ED.EVENT_DATE,TD.TRIP_DATE),'YYYY-MM-DD'),'YYYY-MM-DD') ) CC 
  WHERE CC.POP > 0 ) PP

WHERE 
  NVL(TO_NUMBER(TO_CHAR(PP.BIG_DATE,'YYYY')),9999) IN (2007,2008,2009,2010)
GROUP BY 
  NVL(TO_NUMBER(TO_CHAR(PP.BIG_DATE,'YYYY')),9999)
ORDER BY 
  NVL(TO_NUMBER(TO_CHAR(PP.BIG_DATE,'YYYY')),9999)
;

-- Note: @dummy refers to GFFOS gear_subtype: 1=bottom trawl, 3=midwater trawl
-- getData("fos_bycatch.sql","GFFOS",strSpp="396",major=5:7,mindep=76,maxdep=444,dummy=3,server="GFSH",type="ORA",trusted=F,uid="haighr",pwd="")

