		SELECT F.TRIP_ID, 
			--SUM(CASE WHEN ISNULL(BOTTOM_TOW_IND,0) = 1 THEN 1 ELSE 0 END) AS BOTTOM_TRAWL,
			--SUM(CASE WHEN ISNULL(BOTTOM_TOW_IND,0) = 0 THEN 1 ELSE 0 END) AS MIDWATER_TRAWL
		ISNULL(BOTTOM_TOW_IND,0) AS GEAR
		FROM GFFOS.dbo.GF_FISHING_EVENT F 
		LEFT JOIN GFFOS_Build.dbo.GF_FE_TRAWL_SPECS GFB ON F.FISHING_EVENT_ID = GFB.FISHING_EVENT_ID
		WHERE TRIP_ID IN (399485)
		--GROUP BY F.TRIP_ID

--qu("fos_optA_gear.sql",dbName="GFFOS",strSpp="440")
