--SET NOCOUNT ON

SELECT * FROM
(SELECT
  VT.VESSEL_REGISTRATION_NUMBER,
  COUNT(VT.OBFL_YEAR) AS NYEARS,
  SUM(VT.NTRIPS) AS NTRIPS
FROM 
  (SELECT
    V.VESSEL_REGISTRATION_NUMBER,
    V.OBFL_YEAR,
    COUNT(V.TRIP_ID)AS NTRIPS
  FROM
    (SELECT
      T.VESSEL_REGISTRATION_NUMBER, 
      TO_NUMBER(TO_CHAR(COALESCE(T.TRIP_START_DATE,T.TRIP_END_DATE),'YYYY')) AS OBFL_YEAR,
      T.TRIP_ID
    FROM GFFOS.GF_TRIP T
    GROUP BY
      T.VESSEL_REGISTRATION_NUMBER, 
      TO_NUMBER(TO_CHAR(COALESCE(T.TRIP_START_DATE,T.TRIP_END_DATE),'YYYY')), 
      T.TRIP_ID ) V
  GROUP BY
    V.VESSEL_REGISTRATION_NUMBER, 
    V.OBFL_YEAR) VT
WHERE VT.NTRIPS >=5
GROUP BY
  VT.VESSEL_REGISTRATION_NUMBER) VYT
WHERE VYT.NYEARS >= 3
ORDER BY VYT.VESSEL_REGISTRATION_NUMBER
;


