-- Linking GFFOS to GFBioSQl (NO 250811) but use OFFLOAD tables
-- (RH 260226) updated the code to use GF_MERGED_CATCH instead of D_OFFICIAL_CATCH for better gear information
SET NOCOUNT ON

-- Collect basic offload information (use GFB's FOS_TRIP table rather than link through HAIL_IN, which loses a lot of records)
-- Note: one FOS trip offloads multiple species (no fishing event info because offloads pool fishing events)
-- Had to use aggregates because several instances of multiple offload weights
SELECT --top 1000
  OH.TRIP_ID AS FOS_TRIP_ID,
  OH.OFFLOAD_ID,
  COUNT(OD.OFFLOAD_DETAIL_ID) AS NO_OFFLOAD_DETAILS,  -- some species are recorded more than once in an offload (e.g., 455, 467, 602)
  OH.HAIL_IN_NUMBER,
  OH.OFFLOAD_DATE,
  OH.GEAR,
  OH.OFFLOAD_PORT_CODE,
  OH.OFFLOAD_LOCATION_CODE,
  OH.OFFLOADER_CODE,
  OD.SPECIES_CODE,
  SUM(ISNULL(OD.OFFLOAD_WEIGHT,0)) AS OFFLOAD_WEIGHT,
  OD.WEIGHT_UNIT_CODE,
  T.TRIP_ID AS GFB_TRIP_ID,
  T.TRIP_SUB_TYPE_CODE,
  T.TRIP_START_DATE,
  T.TRIP_END_DATE,
  T.VESSEL_ID,
  T.CAPTAIN_ID
INTO #OFFLOADS
FROM 
  GFFOS.dbo.GF_OFFLOAD_HEADER OH
  INNER JOIN GF_OFFLOAD_DETAIL OD ON
    OH.OFFLOAD_ID = OD.OFFLOAD_ID
  INNER JOIN GFBioSQL.dbo.FOS_TRIP FT ON
    OH.TRIP_ID = FT.FOS_TRIP_ID
  INNER JOIN GFBioSQL.dbo.TRIP T ON
    FT.TRIP_ID = T.TRIP_ID
WHERE 
  T.TRIP_SUB_TYPE_CODE IN (1,4)  -- just get commercial trips
  AND OH.OFFLOAD_PORT_CODE IN (1136, 1123, 1125, 14756) -- Ucluelet, Port Hardy, Prince Rupert, Port Simpson
  AND OH.OFFLOAD_DATE > '2023-03-01'
  --AND OH.GEAR = 'TRAWL' -- gear seems to be 'undefined'
  --AND OH.TRIP_ID IN (435088, 442495, 444213)  -- just for testing
  --AND OH.TRIP_ID IN (447177, 455439, 457021)  -- just for testing
  --AND OH.TRIP_ID IN (438120, 439499, 440776, 441417)  -- just for testing
  --AND OH.TRIP_ID IN (435059, 435088, 435152)  -- just for testing
  --AND OH.TRIP_ID IN (435340)  -- for debugging
  --AND   OD.SPECIES_CODE IN ('222')
GROUP BY
  OH.TRIP_ID,
  OH.OFFLOAD_ID,
  OH.HAIL_IN_NUMBER,
  OH.OFFLOAD_DATE,
  OH.GEAR,
  OH.OFFLOAD_PORT_CODE,
  OH.OFFLOAD_LOCATION_CODE,
  OH.OFFLOADER_CODE,
  OD.SPECIES_CODE,
  OD.WEIGHT_UNIT_CODE,
  T.TRIP_ID,
  T.TRIP_SUB_TYPE_CODE,
  T.TRIP_START_DATE,
  T.TRIP_END_DATE,
  T.VESSEL_ID,
  T.CAPTAIN_ID

-- Create a summary of fishing events for the trip offloads
-- Get unique Trips from offloads above
SELECT
  MIN(OL.FOS_TRIP_ID) AS FOS_TRIP_ID,
--  MIN(OL.HAIL_IN_NUMBER) AS FOS_HAIL_IN,
  MIN(OL.GFB_TRIP_ID) AS GFB_TRIP_ID
INTO #OFFTRIPS
FROM #OFFLOADS OL
GROUP BY
  OL.FOS_TRIP_ID,
--  OL.HAIL_IN_NUMBER,
  OL.GFB_TRIP_ID

-- Using D_OFFICIAL_CATCH
SELECT
  OT.FOS_TRIP_ID, OT.GFB_TRIP_ID,
  ISNULL(DOC.GEAR,'UNKNOWN') AS GEAR,
  ISNULL(DOC.BEST_DEPTH_FM,0.0) AS DEPTH,
  ISNULL(DOC.MAJOR_STAT_AREA_CODE,'00') AS MAJOR,
  ISNULL(DOC.MINOR_STAT_AREA_CODE,'00') AS MINOR,
  ISNULL(DOC.LOCALITY_CODE,0) AS LOCALITY,
  ISNULL(DOC.MAJOR_STAT_AREA_CODE,'00') + '.' + ISNULL(DOC.MINOR_STAT_AREA_CODE,'00') + '.' + CONVERT(VARCHAR(5), ISNULL(DOC.LOCALITY_CODE,0))AS MML, -- Major.Minor.Locality
  ISNULL(DOC.SPECIES_CODE,'XXX') AS SPECIES
INTO #EVENTS_OLD
FROM
  #OFFTRIPS OT
  INNER JOIN GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH DOC ON
    OT.FOS_TRIP_ID = DOC.TRIP_ID


-- Using D_OFFICIAL_CATCH
--SELECT
--  OT.FOS_TRIP_ID, OT.GFB_TRIP_ID,
--  ISNULL(DOC.GEAR,'UNKNOWN') AS GEAR,
--  ISNULL(DOC.BEST_DEPTH_FM,0.0) AS DEPTH,
--  ISNULL(DOC.MAJOR_STAT_AREA_CODE,'00') AS MAJOR,
--  ISNULL(DOC.MINOR_STAT_AREA_CODE,'00') AS MINOR,
--  ISNULL(DOC.LOCALITY_CODE,0) AS LOCALITY,
--  ISNULL(DOC.MAJOR_STAT_AREA_CODE,'00') + '.' + ISNULL(DOC.MINOR_STAT_AREA_CODE,'00') + '.' + CONVERT(VARCHAR(5), ISNULL(DOC.LOCALITY_CODE,0))AS MML, -- Major.Minor.Locality
--  ISNULL(DOC.SPECIES_CODE,'XXX') AS SPECIES
--INTO #EVENTS_DOC
--FROM
--  #OFFTRIPS OT
--  INNER JOIN GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH DOC ON
--    OT.FOS_TRIP_ID = DOC.TRIP_ID

-- Using MERGED_CATCH (because it delineates MW tows)
SELECT
  OT.FOS_TRIP_ID,
  OT.GFB_TRIP_ID,
  ISNULL(MC.GEAR,'UNKNOWN') AS GEAR,
  ISNULL(MC.BEST_DEPTH,0.0) AS DEPTH,
  ISNULL(MC.MAJOR_STAT_AREA_CODE,'00') AS MAJOR,
  ISNULL(MC.MINOR_STAT_AREA_CODE,'00') AS MINOR,
  ISNULL(MC.LOCALITY_CODE,0) AS LOCALITY,
  ISNULL(MC.MAJOR_STAT_AREA_CODE,'00') + '.' + ISNULL(MC.MINOR_STAT_AREA_CODE,'00') + '.' + CONVERT(VARCHAR(5), ISNULL(MC.LOCALITY_CODE,0)) AS MML, -- Major.Minor.Locality
  ISNULL(MC.SPECIES_CODE,'XXX') AS SPECIES
INTO #EVENTS
FROM
  #OFFTRIPS OT
  INNER JOIN GFFOS.dbo.GF_MERGED_CATCH MC ON
    OT.FOS_TRIP_ID = CAST(MC.TRIP_ID AS INT)
WHERE MC.TRIP_ID NOT LIKE '%[a-zA-Z]%'

--SELECT * FROM #EVENTS

-- Use this to summarise fishing events from GFFOS GF_MERGED_CATCH
-- <https://stackoverflow.com/questions/77694328/get-most-common-value-over-group-by-for-multiple-columns>
-- IF OBJECT_ID('#EMODES') IS NOT NULL DROP TABLE #EMODES -- not necessary
-- WHEN without ELSE returns NULL if condition is not met, BUT WHEN needs ELSE to work in Temporary Tables!!!
SELECT  
  T2.FOS_TRIP_ID, T2.GFB_TRIP_ID,
  MAX(CASE WHEN T2.RN1 = 1 THEN T2.GEAR     ELSE ''   END) AS GEAR_MODE,
  MAX(CASE WHEN T2.RN2 = 1 THEN T2.DEPTH    ELSE 0.0  END) * 1.8288 AS DEPTH_MODE,
  MAX(CASE WHEN T2.RN3 = 1 THEN T2.MAJOR    ELSE '00' END) AS MAJOR_MODE,
  MAX(CASE WHEN T2.RN4 = 1 THEN T2.MINOR    ELSE '00' END) AS MINOR_MODE,
  MAX(CASE WHEN T2.RN5 = 1 THEN T2.LOCALITY ELSE 0       END) AS LOCAL_MODE,
  MAX(CASE WHEN T2.RN6 = 1 THEN T2.MML      ELSE '0.0.0' END) AS MML_MODE,
  MAX(CASE WHEN T2.RN7 = 1 THEN T2.SPECIES  ELSE '000'   END) AS SPP_MODE
INTO #EMODES
FROM (
  SELECT  T1.* ,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.GearCnt    DESC, T1.GEAR)     AS RN1,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.DepthCnt   DESC, T1.DEPTH)    AS RN2,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.MajorCnt   DESC, T1.MAJOR)    AS RN3,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.MinorCnt   DESC, T1.MINOR)    AS RN4,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.LocalCnt   DESC, T1.LOCALITY) AS RN5,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.MMLCnt     DESC, T1.MML)      AS RN6,
    ROW_NUMBER() OVER(PARTITION BY T1.FOS_TRIP_ID, T1.GFB_TRIP_ID ORDER BY T1.SpeciesCnt DESC, T1.SPECIES)  AS RN7
  FROM (
    SELECT *,
      COUNT(E.GEAR)  OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.GEAR)  GearCnt,
      COUNT(E.DEPTH) OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.DEPTH) DepthCnt,
      COUNT(E.MAJOR) OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.MAJOR) MajorCnt,
      COUNT(E.MINOR) OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.MINOR) MinorCnt,
      COUNT(E.LOCALITY) OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.LOCALITY) LocalCnt,
      COUNT(E.MML)      OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.MML)      MMLCnt,
      COUNT(E.SPECIES)  OVER(PARTITION BY E.FOS_TRIP_ID, E.GFB_TRIP_ID, E.SPECIES)  SpeciesCnt
    FROM --(
      #EVENTS E
    --) 
  ) T1 -- Tier 1
) T2 -- Tier 2
GROUP BY T2.FOS_TRIP_ID, T2.GFB_TRIP_ID
ORDER BY T2.FOS_TRIP_ID, T2.GFB_TRIP_ID

--SELECT * FROM #EMODES


-- Summarise samples by Trip
SELECT
  OL.GFB_TRIP_ID AS TID_GFB,
  OL.FOS_TRIP_ID AS TID_FOS,
  OL.HAIL_IN_NUMBER AS HAIL,
  OL.OFFLOAD_DATE AS OFF_DATE,
  OL.OFFLOAD_PORT_CODE AS PORT,
  OL.VESSEL_ID AS VID,
  OL.SPECIES_CODE AS SPP_SAMP,
  S.SAMPLE_ID AS SID,
  COUNT(DISTINCT SP.SPECIMEN_ID) AS NFISH,
  SUM(CASE WHEN SP.SPECIMEN_SEX_CODE IN (2) THEN 1 ELSE 0 END) AS NFEM,
  SUM(CASE WHEN SP.SPECIMEN_SEX_CODE IN (1) THEN 1 ELSE 0 END) AS NMAL,
  SUM(CASE WHEN ISNULL(SP.MATURITY_CODE,0) <> 0 THEN 1 ELSE 0 END) AS NMAT,
  SUM(CASE WHEN ISNULL(SP.SPECIMEN_AGE,0) <> 0 THEN 1 ELSE 0 END) AS NAGE,
--  SUM(CASE WHEN ISNULL(SP.SPECIMEN_AGE,0) <> 0 THEN SP.SPECIMEN_AGE ELSE 0 END) AS SAGE,
  SUM(CASE WHEN ISNULL(SP.SPECIMEN_AGE,0) <> 0 THEN SP.SPECIMEN_AGE ELSE 0 END) /   -- AVG with NULLIF does not work for temporary tables
  SUM(CASE WHEN ISNULL(SP.SPECIMEN_AGE,0) <> 0 THEN 1 ELSE 1e-6 END) AS MAGE        -- Cannot divide by 0 if all records are zero
INTO #TRIP_SAMPLES
FROM #OFFLOADS OL
INNER JOIN GFBioSQL.dbo.FISHING_EVENT FE ON
  OL.GFB_TRIP_ID = FE.TRIP_ID
INNER JOIN GFBioSQL.dbo.FISHING_EVENT_CATCH FEC ON
  FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
INNER JOIN GFBioSQL.dbo.CATCH C ON
  FEC.CATCH_ID = C.CATCH_ID
INNER JOIN GFBioSQL.dbo.CATCH_SAMPLE CS ON
  C.CATCH_ID = CS.CATCH_ID
  AND OL.SPECIES_CODE = C.SPECIES_CODE  -- needed to focus on species that were actually sampled, i.e., a small subset of the offloads (like 4 or 5 species) should only be represented in GFBio.
INNER JOIN GFBioSQL.dbo.SAMPLE S ON
  CS.SAMPLE_ID = S.SAMPLE_ID
INNER JOIN GFBioSQL.dbo.SPECIMEN SP ON
  S.SAMPLE_ID = SP.SAMPLE_ID
--WHERE S.SAMPLE_ID IN (584197) -- SGR in 2024
GROUP BY
  OL.GFB_TRIP_ID,
  OL.FOS_TRIP_ID,
  OL.HAIL_IN_NUMBER,
  OL.OFFLOAD_DATE,
  OL.OFFLOAD_PORT_CODE,
  OL.VESSEL_ID,
  OL.SPECIES_CODE,
  S.SAMPLE_ID
ORDER BY
  OL.GFB_TRIP_ID,
  OL.FOS_TRIP_ID,
  OL.HAIL_IN_NUMBER,
  OL.OFFLOAD_DATE,
  OL.OFFLOAD_PORT_CODE,
  OL.VESSEL_ID,
  OL.SPECIES_CODE,
  S.SAMPLE_ID

-- Merge #EMODES (Event modes) and Trip Samples
SELECT
  CONVERT(INTEGER, TS.TID_GFB) AS TID_GFB,
  TS.TID_FOS, TS.HAIL, 
  CONVERT(VARCHAR, TS.OFF_DATE, 20) AS OFF_DATE,
  YEAR(TS.OFF_DATE) AS YEAR,
  MONTH(TS.OFF_DATE) AS MONTH,
  CASE WHEN (MONTH(TS.OFF_DATE) = 2 AND DAY(TS.OFF_DATE) >=21) OR MONTH(TS.OFF_DATE) >= 3 THEN YEAR(TS.OFF_DATE)
    ELSE YEAR(TS.OFF_DATE) - 1 END AS FYEAR,
  TS.PORT, 
  CONVERT(INTEGER, TS.VID) AS VID,
  E.GEAR_MODE, 
  CONVERT(REAL, E.DEPTH_MODE) AS DEPTH_MODE, 
  E.MAJOR_MODE, E.MINOR_MODE, E.LOCAL_MODE, E.MML_MODE, E.SPP_MODE,
  TS.SPP_SAMP, 
  CONVERT(INTEGER, TS.SID) AS SID,
  TS.NFISH, TS.NFEM, TS.NMAL, TS.NMAT, TS.NAGE, 
  CONVERT(REAL, TS.MAGE) AS MAGE
INTO #WHOLE_SHEBANG
FROM
  #EMODES E
  INNER JOIN #TRIP_SAMPLES TS ON
    E.GFB_TRIP_ID = TS.TID_GFB
ORDER BY
  TS.TID_GFB, TS.SID


SELECT * from #WHOLE_SHEBANG --#OFFTRIPS --#OFFLOADS --#TRIP_SAMPLES --#EMODES --

-- qu("fos_gfb_offloads.sql",dbName="GFFOS",strSpp="123", as.is=rep(T,24))


