-- Query to determine catch weight of RFF compared to TFF for Gabe Andrews
SELECT --TOP 100
  MC.LONGITUDE AS X,
  MC.LATITUDE AS Y,
  MC.BEST_DEPTH AS Z,
  CONVERT(SMALLDATETIME,CONVERT(char(10),MC.BEST_DATE, 20)) AS 'date',
  CONVERT(INTEGER, ISNULL(MC.MAJOR_STAT_AREA_CODE,'00')) AS major,
  CONVERT(INTEGER, ISNULL(MC.MINOR_STAT_AREA_CODE,'00')) AS minor,
  ISNULL(MC.LOCALITY_CODE,0) AS locality,
  CASE WHEN MC.VESSEL_REGISTRATION_NUMBER IS NULL OR VESSEL_REGISTRATION_NUMBER=0 THEN ISNULL(MC.VESSEL_NAME,'UNKNOWN')
    ELSE MC.VESSEL_REGISTRATION_NUMBER END AS vessel,

--Flatfish
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('595') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- LEF Left-eyed flounders
    ELSE 0 END) as LEF,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('596') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- PAD Pacific Sanddab
    ELSE 0 END) as PAD,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('598') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SPD Speckled Sanddab
    ELSE 0 END) as SPD,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('599') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RIF Right-eyed flounders
    ELSE 0 END) as REF,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('602') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- ARF Arrowtooth Flounder
    ELSE 0 END) as ARF,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('604') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RSL Roughscale Sole
    ELSE 0 END) as RSL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('605') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- DEL Deepsea Sole
    ELSE 0 END) as DEL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('607') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- PEL Petrale Sole
    ELSE 0 END) as PEL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('610') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RXL Rex Sole
    ELSE 0 END) as RXL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('612') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- FHL Flathead Sole
    ELSE 0 END) as FHL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('614') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- PAH Pacific Halibut
    ELSE 0 END) as PAH,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('617') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- FLL Forkline Sole
    ELSE 0 END) as FLL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('619') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- BUL Butter Sole
    ELSE 0 END) as BUL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('621') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- ROL Rock Sole
    ELSE 0 END) as ROL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('623') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YFL Yellowfin Sole
    ELSE 0 END) as YFL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('625') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SLL Slender Sole
    ELSE 0 END) as SLL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('626') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- DOL Dover Sole
    ELSE 0 END) as DOL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('628') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- ENL English Sole
    ELSE 0 END) as ENL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('631') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- STF Starry Flounder
    ELSE 0 END) as STF,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('633') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- COL C-o Sole
    ELSE 0 END) as COL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('635') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- CUL Curlfin Sole
    ELSE 0 END) as CUL,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('636') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SAL Sand Sole
    ELSE 0 END) as SAL,

--Other fish
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('222') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- PAC Pacific Cod
    ELSE 0 END) as PAC,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('394') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RER|BSR|REBS Rougheye/Blackspotted Rockfish
    ELSE 0 END) as REBS,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('396') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- POP Pacific Ocean Perch
    ELSE 0 END) as POP,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('401') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- RBR Redbanded rockfish
    ELSE 0 END) as RBR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('405') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- SGR Silvergray rockfish
    ELSE 0 END) as SGR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('418') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YTR Yellowtail rockfish
    ELSE 0 END) as YTR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('440') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- YMR Yellowmouth Rockfish
    ELSE 0 END) as YMR,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('453') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- LST Longspine Thornyhead
    ELSE 0 END) as LST,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('467') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- LIN Lingcod
    ELSE 0 END) as LIN,

-- Corals and sponges
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('2A0') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 2A0 Sponges
    ELSE 0 END) as UIS,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('2A1') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 2A0 Calcareous sponges
    ELSE 0 END) as CAS,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('2I0') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 2I0 Glass sponges
    ELSE 0 END) as GLS,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('2Q0') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 2Q0 Bath sponges
    ELSE 0 END) as BAS,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('3J2') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 3J2 Stony corals
    ELSE 0 END) as STC,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('3R0') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 3R0 Soft corals
    ELSE 0 END) as SOC,
  SUM(CASE
    WHEN MC.SPECIES_CODE IN ('3S0') THEN ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0)  -- 3S0 Gorgonian corals
    ELSE 0 END) as GOC

FROM 
  GF_MERGED_CATCH MC
WHERE
  Year(MC.BEST_DATE) BETWEEN 1996 AND 2024
  AND MC.LONGITUDE IS NOT NULL
  AND MC.LATITUDE IS NOT NULL
  AND MC.BEST_DEPTH IS NOT NULL
  AND MC.MAJOR_STAT_AREA_CODE IN ('03','04','05','06','07','08','09')
  --AND MC.GEAR IN ('MIDWATER TRAWL')
  AND MC.GEAR IN ('BOTTOM TRAWL', 'UNKNOWN TRAWL')
  --AND MC.GEAR IN ('BOTTOM TRAWL', 'MIDWATER TRAWL', 'UNKNOWN TRAWL')
GROUP BY
  MC.LONGITUDE,
  MC.LATITUDE,
  MC.BEST_DEPTH,
  CONVERT(SMALLDATETIME,CONVERT(char(10),MC.BEST_DATE, 20)),
  CONVERT(INTEGER, ISNULL(MC.MAJOR_STAT_AREA_CODE,'00')),
  CONVERT(INTEGER, ISNULL(MC.MINOR_STAT_AREA_CODE,'00')),
  ISNULL(MC.LOCALITY_CODE,0),
  CASE WHEN MC.VESSEL_REGISTRATION_NUMBER IS NULL OR VESSEL_REGISTRATION_NUMBER=0 THEN ISNULL(MC.VESSEL_NAME,'UNKNOWN')
    ELSE MC.VESSEL_REGISTRATION_NUMBER END

--qu("fos_clara_ff+_bt.sql", dbName="GFFOS", strSpp="999")
