SET NOCOUNT ON 
-- Mean species weight calculated using `gfb_mean_weight.sql', which emulates PJS algorithm for GFBIO data
@INSERT('meanSppWt.sql')  -- getData now inserts the specified SQL file assuming it's on the `path' specified in `getData'

SELECT --top 500
  Year(MC.BEST_DATE) AS 'year', 
  MC.FISHING_EVENT_ID AS 'FEID',
  MC.SPECIES_CODE AS 'spp',
  ISNULL(MC.MAJOR_STAT_AREA_CODE,'00') AS 'major',
  ISNULL(MC.MINOR_STAT_AREA_CODE,'00') AS 'minor',
  ISNULL(MC.LOCALITY_CODE,0) AS 'locality',
  ISNULL(MC.BEST_DEPTH,0) AS 'depth',
  CASE
    WHEN MC.GEAR IN ('BOTTOM TRAWL','UNKNOWN TRAWL') THEN 1
    WHEN MC.GEAR IN ('TRAP') THEN 2
    WHEN MC.GEAR IN ('MIDWATER TRAWL') THEN 3
    WHEN MC.GEAR IN ('HOOK AND LINE') THEN 4
    WHEN MC.GEAR IN ('LONGLINE') THEN 5
    ELSE 0 END AS 'gear',
  COALESCE(NULLIF(MC.LANDED_KG,0), NULLIF(MC.LANDED_PCS*ISNULL(FW.MNWT,1),0), 0) AS 'landed',
  COALESCE(NULLIF(MC.DISCARDED_KG,0), NULLIF(MC.DISCARDED_PCS*ISNULL(FW.MNWT,1),0), 0) AS 'discard',
  COALESCE(NULLIF(MC.LANDED_KG,0), NULLIF(MC.LANDED_PCS*ISNULL(FW.MNWT,1),0), 0) + 
    COALESCE(NULLIF(MC.DISCARDED_KG,0), NULLIF(MC.DISCARDED_PCS*ISNULL(FW.MNWT,1),0), 0) AS 'catch',
  --ISNULL(MC.LANDED_KG,0) AS 'landed',
  --ISNULL(MC.DISCARDED_KG,0) AS 'discard',
  --ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0) AS 'catch',
  COALESCE(TS.SPECIES_CODE,'000') AS 'target'
FROM
  (dbo.GF_MERGED_CATCH MC LEFT OUTER JOIN
  @MEAN_WEIGHT FW ON
    MC.SPECIES_CODE = FW.SPECIES_CODE) LEFT OUTER JOIN
  --dbo.GF_MERGED_CATCH MC  LEFT OUTER JOIN
  dbo.GF_FE_TARGET_SPECIES TS
  ON MC.FISHING_EVENT_ID = CAST(TS.FISHING_EVENT_ID AS CHAR)
WHERE
  TS.PRIORITY=1 AND
  year(MC.BEST_DATE) BETWEEN 1996 and 2024 AND
  --ISNULL(MC.BEST_DEPTH,0) > 0 AND
  --ISNULL(MC.LANDED_KG,0) + ISNULL(MC.DISCARDED_KG,0) > 0
  COALESCE(NULLIF(MC.LANDED_KG,0), NULLIF(MC.LANDED_PCS*ISNULL(FW.MNWT,1),0), 0) + 
    COALESCE(NULLIF(MC.DISCARDED_KG,0), NULLIF(MC.DISCARDED_PCS*ISNULL(FW.MNWT,1),0), 0) > 0


-- qu("fos_gabe_andrews.sql",dbName="GFFOS",strSpp="123", as.is=c(F,F,T,rep(F,8),T))

