-- Query species catch from GFFOS on GFSH
SELECT
--  CC.FID AS \"fid\",
  (CASE 
    WHEN NVL(TO_CHAR(CC.Edate,'YYYY'),'0') IN '0206' THEN 2006
    ELSE TO_NUMBER(NVL(TO_CHAR(CC.Edate,'YYYY'),'0')) END) AS \"year\",
  NVL(TO_CHAR(CC.Edate,'MM'),0) AS \"month\",
  CC.depth AS \"depth\",
  (CASE WHEN CC.major IN ('99') THEN '00' ELSE CC.major END) AS \"major\",
  (CASE WHEN CC.minor IN ('99') THEN '00' ELSE CC.minor END) AS \"minor\",
  (CASE WHEN CC.locality IN (99) THEN 0 ELSE CC.locality END) AS \"locality\",
  CC.gear AS \"gear\",
  CC.Y AS \"latitude\",
  CC.VRN AS \"vessel\",
  CC.effort AS \"effort\",
  CC.landed + CC.released + CC.liced + CC.bait AS \"catch\",
  CC.bycatch AS \"bycatch\"
FROM 
  (SELECT
  OC.TRIP_ID,
  OC.FISHING_EVENT_ID,
  (CASE
    WHEN OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND 
      OC.GEAR_SUBTYPE IN ('HARD BOTTOM TRAWL','SOFT BOTTOM TRAWL') THEN 1  -- quick fix for now
    WHEN OC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') THEN 2
    WHEN OC.FISHERY_SECTOR IN ('SABLEFISH') THEN 3
    WHEN OC.FISHERY_SECTOR IN ('LINGCOD','SPINY DOGFISH') THEN 4
    WHEN OC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') THEN 5
    ELSE 0 END) AS FID,
  TO_DATE(TO_CHAR(OC.BEST_DATE,'YYYY-MM-DD'),'YYYY-MM-DD') AS Edate,
  NVL(OC.MAJOR_STAT_AREA_CODE,'00') AS major,
  NVL(OC.MINOR_STAT_AREA_CODE,'00') AS minor,
  NVL(OC.LOCALITY_CODE,0) AS locality,
  (CASE
    WHEN OC.GEAR IN ('TRAWL') AND OC.GEAR_SUBTYPE NOT IN ('MIDWATER TRAWL') THEN 1
    WHEN OC.GEAR IN ('TRAP')  THEN 2
    WHEN OC.GEAR IN ('TRAWL') AND OC.GEAR_SUBTYPE IN ('MIDWATER TRAWL') THEN 3
    WHEN OC.GEAR IN ('HOOK AND LINE')  THEN 4
    WHEN OC.GEAR IN ('LONGLINE')  THEN 5
    ELSE 0 END) AS gear,
  NVL(OC.VESSEL_REGISTRATION_NUMBER,0) AS VRN,
  Avg(COALESCE(OC.START_LATITUDE,OC.END_LATITUDE,NULL)) AS Y,
  Avg(NVL(OC.BEST_DEPTH_FM,NULL) * 6. * 0.3048) AS depth,  -- convert fathoms to metres
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      NVL(OC.LANDED_ROUND_KG,0)
    ELSE 0 END) AS landed,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.mnwt, 0)
    ELSE 0 END) AS released,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
	    (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.mnwt
	  ELSE 0 END) AS liced,
  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@sppcode) THEN
      (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.mnwt
    ELSE 0 END) AS bait,

  Sum(CASE
    WHEN OC.SPECIES_CODE IN (@tarcode) THEN
      NVL(OC.LANDED_ROUND_KG,0) +                                                          --landed
      COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.mnwt, 0) + -- released
	   (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.mnwt +           -- liced
      (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.mnwt               -- bait
    ELSE 0 END) AS bycatch,

  Avg(
    CASE WHEN OC.START_DATE IS NOT NULL AND OC.END_DATE IS NOT NULL THEN
    TO_NUMBER(OC.END_DATE - OC.START_DATE) * 24. * 60. ELSE 0 END) AS effort,   --effort in minutes
  Sum(
    NVL(OC.LANDED_ROUND_KG,0) +
    COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.mnwt, 0) +
    (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.mnwt +
    (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.mnwt
    ) AS totcat
  FROM GFFOS.GF_D_OFFICIAL_FE_CATCH OC INNER JOIN
-- FISH WEIGHTS FW
  GFFOS.MEAN_SPECIES_WEIGHT_VW FW ON
    OC.SPECIES_CODE = FW.spp
  GROUP 
    BY OC.TRIP_ID, OC.FISHING_EVENT_ID,
  (CASE
    WHEN OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL')  AND 
      OC.GEAR_SUBTYPE IN ('HARD BOTTOM TRAWL','SOFT BOTTOM TRAWL') THEN 1
    WHEN OC.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH') THEN 2
    WHEN OC.FISHERY_SECTOR IN ('SABLEFISH') THEN 3
    WHEN OC.FISHERY_SECTOR IN ('LINGCOD','SPINY DOGFISH') THEN 4
    WHEN OC.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE') THEN 5
    ELSE 0 END),
  TO_DATE(TO_CHAR(OC.BEST_DATE,'YYYY-MM-DD'),'YYYY-MM-DD'),
  NVL(OC.MAJOR_STAT_AREA_CODE,'00'),
  NVL(OC.MINOR_STAT_AREA_CODE,'00'),
  NVL(OC.LOCALITY_CODE,0),
  (CASE
    WHEN OC.GEAR IN ('TRAWL') AND OC.GEAR_SUBTYPE NOT IN ('MIDWATER TRAWL') THEN 1
    WHEN OC.GEAR IN ('TRAP')  THEN 2
    WHEN OC.GEAR IN ('TRAWL') AND OC.GEAR_SUBTYPE IN ('MIDWATER TRAWL') THEN 3
    WHEN OC.GEAR IN ('HOOK AND LINE')  THEN 4
    WHEN OC.GEAR IN ('LONGLINE')  THEN 5
    ELSE 0 END),
  NVL(OC.VESSEL_REGISTRATION_NUMBER,0) ) CC
WHERE
--  CC.FID IN (1) AND
  (CASE 
    WHEN NVL(TO_CHAR(CC.Edate,'YYYY'),'0') IN ('0206') THEN 2006
    ELSE TO_NUMBER(NVL(TO_CHAR(CC.Edate,'YYYY'),'0')) END) > 0 AND
  NVL(CC.depth,0) > 0 AND
  NVL(CC.Y,0) > 0 AND
  NVL(CC.effort,0) > 0
;
-- getData("fos_glm.sql","GFFOS",strSpp="440",tarSpp="396",server="GFSH",type="ORA",trusted=F)

