-- SQL code to get IPHC longline set data (for AME's IPHC index calculation) from GFBioSQL
-- Last modified: 2015-03-04

SET NOCOUNT ON -- prevents timeout errors

SELECT
  YEAR(T.TRIP_START_DATE) AS [year],
  T.TRIP_ID,
  FE.FISHING_EVENT_ID,
  FE.BLOCK_DESIGNATION,
  FE.FE_MAJOR_LEVEL_ID,
  C.SPECIES_CODE,
  C.CATCH_WEIGHT,
  C.CATCH_COUNT,
  S.SURVEY_SERIES_ID,
  LS.LGLSP_HOOKS_SET_COUNT,
  LS.SKATE_COUNT,
  ES.EFFECTIVE_SKATE,
  C.SPECIES_CATEGORY_CODE,
  CASE WHEN FE.FE_START_LONGITUDE_DEGREE IS NULL THEN 0. ELSE
    FE.FE_START_LONGITUDE_DEGREE + ISNULL(FE.FE_START_LONGITUDE_MINUTE,0.)/60. END AS START_LONGITUDE,
  CASE WHEN FE.FE_END_LONGITUDE_DEGREE IS NULL THEN 0. ELSE 
    FE.FE_END_LONGITUDE_DEGREE + ISNULL(FE.FE_END_LONGITUDE_MINUTE,0.)/60. END AS END_LONGITUDE,
  CASE WHEN FE.FE_START_LATTITUDE_DEGREE IS NULL THEN 0. ELSE 
    FE.FE_START_LATTITUDE_DEGREE + ISNULL(FE.FE_START_LATTITUDE_MINUTE,0.)/60. END AS START_LATITUDE,
  CASE WHEN FE.FE_END_LATTITUDE_DEGREE IS NULL THEN 0. ELSE
    FE.FE_END_LATTITUDE_DEGREE + ISNULL(FE.FE_END_LATTITUDE_MINUTE,0.)/60. END AS END_LATITUDE
FROM
  (((TRIP_SURVEY TS INNER JOIN
  SURVEY S ON
    TS.SURVEY_ID = S.SURVEY_ID) INNER JOIN
  (((B02_FISHING_EVENT FE INNER JOIN
  B02L3_Link_Fishing_Event_Catch L23 ON
    FE.FISHING_EVENT_ID = L23.FISHING_EVENT_ID) INNER JOIN
  B03_CATCH C ON
    L23.CATCH_ID = C.CATCH_ID) INNER JOIN
  B01_TRIP T ON
    FE.TRIP_ID = T.TRIP_ID) ON
    TS.TRIP_ID = T.TRIP_ID) LEFT OUTER JOIN
  LONGLINE_SPECS LS ON
    FE.FISHING_EVENT_ID = LS.FISHING_EVENT_ID) LEFT OUTER JOIN
  IPHC_EFFECTIVE_SKATE ES ON
    FE.FISHING_EVENT_ID = ES.FISHING_EVENT_ID
WHERE
  S.SURVEY_SERIES_ID IN (14) AND
  FE.FE_MINOR_LEVEL_ID Is Null
ORDER BY
  Year(T.TRIP_START_DATE),
  T.TRIP_ID,
  FE.FISHING_EVENT_ID,
  FE.FE_MAJOR_LEVEL_ID,
  C.SPECIES_CODE

--qu("gfb_iphc_set_data.sql",dbName="GFBioSQL",strSpp="442")
--getData("gfb_iphc_set_data.sql",dbName="GFBioSQL",strSpp="442",path="C:/Users/haighr/Files/Projects/R/Develop/PBStools/Authors/SQLcode/")
--qu("gfb_iphc_set_data.sql",dbName="GFBioSQL",strSpp="394")
