-- Get age precision data from GFBioSQL (last revised 2018-06-21)
-- Used gfplot's `get-age-precision.sql' from https://github.com/pbs-assess/gfplot/blob/master/inst/sql/get-age-precision.sql

SET NOCOUNT ON

SELECT
  SA.SPECIMEN_ID AS SPID, 
  YEAR(SM.SAMPLE_DATE) AS year, 
  C.SPECIES_CODE AS spp, 
  S.SPECIES_COMMON_NAME AS spn, 
  SA.AGE_READING_TYPE_CODE as atype,
  AM.AGEING_METHOD_DESC as adesc, 
  SA.SPECIMEN_AGE as age,
  SA.MINIMUM_AGE as amin,
  SA.MAXIMUM_AGE as amax,
  SA.EMPLOYEE_ID as EMID,
  SA.AGE_READING_ID ARID,
  CASE
    WHEN S.SPECIES_COMMON_NAME = 'NORTH PACIFIC SPINY DOGFISH' AND SA.AGEING_METHOD_CODE=11 THEN SA.AGEING_METHOD_CODE
    WHEN S.SPECIES_COMMON_NAME = 'WALLEYE POLLOCK' AND SA.AGEING_METHOD_CODE=7 THEN SA.AGEING_METHOD_CODE
    WHEN S.SPECIES_COMMON_NAME IN ('LINGCOD', 'PACIFIC COD') AND SA.AGEING_METHOD_CODE=6 THEN SA.AGEING_METHOD_CODE
    WHEN S.SPECIES_COMMON_NAME IN ('SHORTRAKER ROCKFISH', 'SHORTSPINE THORNYHEAD', 'LONGSPINE THORNYHEAD') AND SA.AGEING_METHOD_CODE IN (1,3,4,17) THEN  SA.AGEING_METHOD_CODE
    WHEN S.SPECIES_COMMON_NAME IN ('BIG SKATE',
	'LONGNOSE SKATE',
	'BASKING SHARK',
	'SALMON SHARK',
	'BROWN CAT SHARK',
	'BLUE SHARK',
	'PACIFIC SLEEPER SHARK',
	'ALEUTIAN SKATE',
	'ABYSSAL SKATE',
	'BROAD SKATE',
	'ROUGHTAIL SKATE',
	'SANDPAPER SKATE') AND SA.AGEING_METHOD_CODE = 12 THEN SA.AGEING_METHOD_CODE
	WHEN SPECIES_COMMON_NAME IN ('PACIFIC HAKE', 
	'ROUGHEYE/BLACKSPOTTED ROCKFISH COMPLEX', 
	'PACIFIC OCEAN PERCH',
	'REDBANDED ROCKFISH',
	'SILVERGRAY ROCKFISH',
	'COPPER ROCKFISH',
	'DARKBLOTCHED ROCKFISH',
	'WIDOW ROCKFISH',
	'YELLOWTAIL ROCKFISH',
	'QUILLBACK ROCKFISH',
	'BOCACCIO',	
	'CANARY ROCKFISH',
	'REDSTRIPE ROCKFISH',
	'YELLOWMOUTH ROCKFISH',
	'YELLOWEYE ROCKFISH',
	'SABLEFISH',
	'ARROWTOOTH FLOUNDER',
	'PETRALE SOLE',
	'REX SOLE',
	'SOUTHERN ROCK SOLE',
	'DOVER SOLE',
	'ENGLISH SOLE') AND SA.AGEING_METHOD_CODE IN (1,3,17) THEN SA.AGEING_METHOD_CODE END AS ameth
FROM
  AGEING_METHOD AM 
  INNER JOIN SPECIMEN_AGE SA ON
    AM.AGEING_METHOD_CODE = SA.AGEING_METHOD_CODE 
  LEFT OUTER JOIN CATCH_SAMPLE CS
  INNER JOIN SAMPLE SM ON 
    CS.SAMPLE_ID = SM.SAMPLE_ID 
  INNER JOIN CATCH C ON 
    CS.CATCH_ID = C.CATCH_ID ON
    SA.SAMPLE_ID = SM.SAMPLE_ID
  INNER JOIN SPECIES S ON
    S.SPECIES_CODE = C.SPECIES_CODE
WHERE
  SA.AGE_READING_TYPE_CODE IN (2,3) AND
  C.SPECIES_CODE IN (@sppcode)
ORDER BY SA.AGEING_METHOD_CODE

-- qu("gfb_age_precision.sql", dbName="GFBioSQL", strSpp="439")
