SELECT 
  MC.DATABASE_NAME,
  MC.TRIP_ID,
  MC.FISHING_EVENT_ID,
  --MC.SPECIES_CODE,
  MC.FE_START_DATE,
  MC.FE_END_DATE,
  DATEDIFF(n,MC.FE_START_DATE,MC.FE_END_DATE) AS BIG_EFFORT
FROM GF_MERGED_CATCH MC
WHERE
  ABS(DATEDIFF(n,MC.FE_START_DATE,MC.FE_END_DATE)) > 1440
GROUP BY
  MC.DATABASE_NAME,
  MC.TRIP_ID,
  MC.FISHING_EVENT_ID,
  --MC.SPECIES_CODE,
  MC.FE_START_DATE,
  MC.FE_END_DATE,
  DATEDIFF(n,MC.FE_START_DATE,MC.FE_END_DATE)
ORDER BY 
  ABS(DATEDIFF(n,MC.FE_START_DATE,MC.FE_END_DATE)) DESC

