/* PH3_CATCH_SUMMARY copied from PacHarv3 to GFFOS*/
SELECT TOP 100
  CS.STP_SPER_YR AS 'year',
  CS.SP_SPECIES_CDE AS 'species',
  (CASE
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (13,14,15,16,17,18,19,20,28,29,9200,9791,9792,9793,9794) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (11) AND CS.SFA_SMALL_FA_CDE BETWEEN 3 AND 10) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (12) AND CS.SFA_SMALL_FA_CDE NOT IN (12,14,15))  THEN 1
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (21,22,23,24,121,123,9210,9230,9240) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (124) AND CS.SFA_SMALL_FA_CDE BETWEEN 0 AND 3) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (125) AND CS.SFA_SMALL_FA_CDE IN (6) )  THEN 3
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (25,26,126,9250,9260,9270) OR 
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (27) AND CS.SFA_SMALL_FA_CDE NOT IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (124) AND CS.SFA_SMALL_FA_CDE IN (4)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (125) AND CS.SFA_SMALL_FA_CDE BETWEEN 0 AND 5) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (127) AND CS.SFA_SMALL_FA_CDE IN (0,1,2))  THEN 4
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (111,9110) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (10) AND CS.SFA_SMALL_FA_CDE IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (11) AND CS.SFA_SMALL_FA_CDE IN (0,1,2)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (12) AND CS.SFA_SMALL_FA_CDE IN (12,14,15)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (27) AND CS.SFA_SMALL_FA_CDE IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (111) AND CS.SFA_SMALL_FA_CDE IN (0)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (127) AND CS.SFA_SMALL_FA_CDE IN (3,4)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (130) AND CS.SFA_SMALL_FA_CDE IN (1))  THEN 5
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (8,9,108,109,110,9070,9080,9090,9100) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (2) AND CS.SFA_SMALL_FA_CDE IN (18,19)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (7) AND CS.SFA_SMALL_FA_CDE IN (0,1,17,18,19,20,21,23,25,26,27,28)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (10) AND CS.SFA_SMALL_FA_CDE NOT IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (102) AND CS.SFA_SMALL_FA_CDE IN (3)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (107) AND CS.SFA_SMALL_FA_CDE NOT IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (130) AND CS.SFA_SMALL_FA_CDE NOT IN (1))  THEN 6
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (6,106,9021,9060) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (2) AND CS.SFA_SMALL_FA_CDE BETWEEN 2 AND 17) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (5) AND CS.SFA_SMALL_FA_CDE IN (13,16,17,18,19,22,24)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (7) AND CS.SFA_SMALL_FA_CDE BETWEEN 2 AND 16) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (7) AND CS.SFA_SMALL_FA_CDE IN (22,24,29,30,31,32)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (102) AND CS.SFA_SMALL_FA_CDE IN (0,2)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (105) AND CS.SFA_SMALL_FA_CDE IN (2)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (107) AND CS.SFA_SMALL_FA_CDE IN (1))  THEN 7
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (3,4,103,104,8021,9031,9032,9033,9040,9050) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (1) AND CS.SFA_SMALL_FA_CDE NOT IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (2) AND CS.SFA_SMALL_FA_CDE IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (5) AND CS.SFA_SMALL_FA_CDE BETWEEN 0 AND 12) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (5) AND CS.SFA_SMALL_FA_CDE IN (14,15,20,21,23)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (101) AND CS.SFA_SMALL_FA_CDE BETWEEN 4 AND 10) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (102) AND CS.SFA_SMALL_FA_CDE IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (105) AND CS.SFA_SMALL_FA_CDE IN (0,1))  THEN 8
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (142,8022,9010,9022) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (1) AND CS.SFA_SMALL_FA_CDE IN (1)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (2) AND CS.SFA_SMALL_FA_CDE IN (0)) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (2) AND CS.SFA_SMALL_FA_CDE BETWEEN 31 AND 100) OR
        (CS.SFA_MSFA_MIDSIZE_FA_CDE IN (101) AND CS.SFA_SMALL_FA_CDE IN (0,1,2,3))  THEN 9
    ELSE 0 END) AS 'major',
    (CASE
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (142) AND CS.SFA_SMALL_FA_CDE IN (1) THEN 34 /* for POP in Anthony Island (606 records) */
    ELSE 0 END) AS 'minor',
    (CASE
    WHEN CS.SFA_MSFA_MIDSIZE_FA_CDE IN (142) AND CS.SFA_SMALL_FA_CDE IN (1) THEN 1 /* for POP in Anthony Island (606 records) */
    ELSE 0 END) AS 'locality',
  (CONVERT(VARCHAR(10),CS.SFA_MSFA_MIDSIZE_FA_CDE) + '-') + CONVERT(VARCHAR(10),CS.SFA_SMALL_FA_CDE) AS 'region', 
  'CA' AS 'nation',
  CS.CATSUM_ROUND_LBS_WT AS 'catch',
  'lbs' AS 'units',
  CS.GR_GEAR_CDE AS 'gear_code',
  (CASE 
    WHEN CS.GR_GEAR_CDE IN (44,45,46,50,51,57,59,99) THEN 'trawl'
    WHEN CS.GR_GEAR_CDE IN (65,68,86,90,91,92,93,94,95,97,98) THEN 'trap'
    WHEN CS.GR_GEAR_CDE IN (40,30,31,32,33,43,7,36,41,42) THEN 'h&l'
    ELSE 'unk' END) AS 'gear'
  FROM
    PH3_CATCH_SUMMARY CS
  WHERE
    CS.CU_CATCH_UTLZTN_CDE NOT IN (6,22,23,24,27,28) AND
    CS.CATSUM_FISHERY_TYPE_CDE IN ('01','02','03','25') AND
    (CS.STP_SPER_YR >=1982 AND CS.STP_SPER_YR <=1995)
  ORDER BY
    CS.STP_SPER_YR

--qu("ph3_historical.sql", dbName="GFFOS", strSpp="123")

