-- PacHarvest query for fish group catches (2010-10-15)
SET NOCOUNT ON  -- prevents timeout errors

SELECT
  MC.HAIL_IN_NO, 
  MC.SET_NO, 
  OC.OFFLOAD_DATE,
  OC.MAJOR_STAT_AREA,
  OC.MINOR_STAT_AREA,
  POP = Sum(CASE
    WHEN MC.SPECIES_CODE IN ('396') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  ROCKFISH = Sum(CASE
    WHEN S.Rockfish IN (1) AND MC.SPECIES_CODE NOT IN ('396') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  TURBOT = Sum(CASE
    WHEN MC.SPECIES_CODE IN ('602') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  FLATFISH = Sum(CASE
    WHEN S.Flatfish IN (1) AND MC.SPECIES_CODE NOT IN ('602') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  HAKE = Sum(CASE
    WHEN MC.SPECIES_CODE IN ('224','225') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  SHARKS = Sum(CASE
    WHEN S.Class IN (2) AND MC.SPECIES_CODE NOT IN ('065','066') THEN MC.LANDED + MC.DISCARDED
    ELSE 0 END ),
  ALLFISH = Sum(MC.LANDED + MC.DISCARDED)
INTO #GroupCatch
FROM 
  C_Species S 
  RIGHT OUTER JOIN (D_Merged_Catches MC 
    LEFT OUTER JOIN D_Official_Catch OC ON
      MC.HAIL_IN_NO = OC.HAIL_IN_NO AND 
      MC.SET_NO = OC.SET_NO AND 
      MC.SPECIES_CODE = OC.SPECIES_CODE) ON
    S.SPECIES_CDE = MC.SPECIES_CODE
WHERE
  S.Fish IN (1)
GROUP BY 
  MC.HAIL_IN_NO, MC.SET_NO,
  OC.OFFLOAD_DATE, OC.MAJOR_STAT_AREA, OC.MINOR_STAT_AREA
  
SELECT * 
INTO #POPGroups 
FROM #GroupCatch GC 
WHERE GC.POP > 0 

SELECT
  FE.OBFL_HAIL_IN_NO,
  'FDEPTH' = AVG(COALESCE(
    NULLIF(FE.Fishing_Depth,0), NULLIF(FE.OBFL_START_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_END_BOTTOM_DTH,0), NULLIF(FE.OBFL_MID_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_MIN_DTH,0), NULLIF(FE.OBFL_MAX_DTH,0), 0))
INTO #HailDepth
FROM 
  B3_Fishing_Events FE
GROUP BY 
  FE.OBFL_HAIL_IN_NO

SELECT
  'year' = isNull(Year(COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,C.OFFLOAD_DATE)),9999),
  'POP'      = SUM(C.POP)/1000.,
  'rockfish' = SUM(C.ROCKFISH)/1000.,
  'turbot'   = SUM(C.TURBOT)/1000.,
  'flatfish' = SUM(C.FLATFISH)/1000.,
  'hake'     = SUM(C.HAKE)/1000.,
  'sharks'   = SUM(C.SHARKS)/1000.,
  'other'    = SUM(C.ALLFISH-C.POP-C.ROCKFISH-C.TURBOT-C.FLATFISH-C.HAKE-C.SHARKS)/1000.
FROM 
  #HailDepth D 
  RIGHT OUTER JOIN (B3_Fishing_Events E 
    RIGHT OUTER JOIN #POPGroups C ON
      E.OBFL_HAIL_IN_NO = C.HAIL_IN_NO AND 
      E.OBFL_SET_NO = C.SET_NO) ON
    D.OBFL_HAIL_IN_NO = E.OBFL_HAIL_IN_NO
WHERE 
  COALESCE(E.OBFL_MAJOR_STAT_AREA_CDE, C.MAJOR_STAT_AREA, 0) IN (@major) AND 
  COALESCE(E.Fishing_Depth, D.FDEPTH, 0) BETWEEN @mindep AND @maxdep AND
  COALESCE(E.OBFL_GEAR_SUBTYPE_CDE,1) IN (@dummy)
GROUP BY 
  isNull(Year(COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,C.OFFLOAD_DATE)),9999)
ORDER BY 
  isNull(Year(COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,C.OFFLOAD_DATE)),9999)


-- Note: @dummy refers to PacHarvest gear_subtype: 1=bottom trawl, 3=midwater trawl
-- getData("pht_bycatch.sql","PacHarvest", strSpp="396",major=5:7,mindep=76,maxdep=444,dummy=3)


