-- Query to get the fishing depth of species. (RH 2015-10-28)
-- Eventually just query Norm's `GF_MERGED_CATCH' in GFFOS
SET NOCOUNT ON

@INSERT('meanSppWt.sql')  -- getData now inserts the specified SQL file assuming it's on the path specified in getData

-- Grab the depth data from PacHarvest
SELECT
  FE.OBFL_HAIL_IN_NO,
  'FDEPTH' = AVG(COALESCE(
    NULLIF(FE.Fishing_Depth,0), NULLIF(FE.OBFL_START_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_END_BOTTOM_DTH,0), NULLIF(FE.OBFL_MID_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_MIN_DTH,0), NULLIF(FE.OBFL_MAX_DTH,0), 0))
INTO #HailDepth
FROM 
  B3_Fishing_Events FE
GROUP BY 
  FE.OBFL_HAIL_IN_NO

SELECT --TOP 100
  'fid'   = 1,
  'sector' = 'GROUNDFISH TRAWL',
  'year'  = isNull(Year(COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,OC.OFFLOAD_DATE)),9999),
  'date'  = CONVERT(VARCHAR(10),COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,OC.OFFLOAD_DATE),20),
  'major' = COALESCE(E.OBFL_MAJOR_STAT_AREA_CDE, OC.MAJOR_STAT_AREA, 0),
  'minor' = COALESCE(E.OBFL_MINOR_STAT_AREA_CDE, OC.MINOR_STAT_AREA, 0),
  'locality' = COALESCE(E.OBFL_LOCALITY_CDE, OC.LOCALITY_CDE, 0),
  'dfoa'  = COALESCE(E.OBFL_DFO_MGMT_AREA_CDE,OC.DFO_MGMT_AREA_CDE,0),
  'dfos'  = COALESCE(E.OBFL_DFO_MGMT_SUBAREA_CDE,OC.DFO_MGMT_SUBAREA_CDE,0),
  'srfa'  = E.SRF_Major_Area1, 
  'depth' = COALESCE(E.Fishing_Depth, D.FDEPTH, 0),
  'catch' = (MC.LANDED + MC.DISCARDED),
  'gear'  = COALESCE(E.OBFL_GEAR_SUBTYPE_CDE,1)
INTO #PHTDEP
FROM 
  D_Merged_Catches MC 
  LEFT OUTER JOIN D_Official_Catch OC ON
    MC.HAIL_IN_NO = OC.HAIL_IN_NO AND 
    MC.SET_NO = OC.SET_NO AND 
    MC.SPECIES_CODE = OC.SPECIES_CODE
  LEFT OUTER JOIN B3_Fishing_Events E ON
    E.OBFL_HAIL_IN_NO = MC.HAIL_IN_NO AND 
    E.OBFL_SET_NO = MC.SET_NO
  LEFT OUTER JOIN #HailDepth D ON
    D.OBFL_HAIL_IN_NO = E.OBFL_HAIL_IN_NO
WHERE 
  COALESCE(E.Fishing_Depth, D.FDEPTH, 0) > 0 AND
  COALESCE(E.OBFL_MAJOR_STAT_AREA_CDE, OC.MAJOR_STAT_AREA, 0) in (@major) AND
  MC.SPECIES_CODE IN (@sppcode) AND
  E.OBFL_LOG_TYPE_CDE IN ('OBSERVRLOG') AND   -- flag for consideration (observerlogs only)
  (MC.LANDED + MC.DISCARDED) > 1

SELECT --TOP 100
  -- C.TRIP_ID, C.FISHING_EVENT_ID, C.SPECIES_CODE,
  (CASE
    WHEN C.FISHERY_SECTOR IN ('GROUNDFISH TRAWL','JOINT VENTURE TRAWL') THEN 1
    WHEN C.FISHERY_SECTOR IN ('HALIBUT','HALIBUT AND SABLEFISH','K/L') THEN 2
    WHEN C.FISHERY_SECTOR IN ('SABLEFISH') THEN 3
    WHEN C.FISHERY_SECTOR IN ('LINGCOD','SPINY DOGFISH','SCHEDULE II') THEN 4
    WHEN C.FISHERY_SECTOR IN ('ROCKFISH INSIDE','ROCKFISH OUTSIDE','ZN','K/ZN') THEN 5
    WHEN C.FISHERY_SECTOR IN ('FOREIGN') THEN 9
    ELSE 0 END) AS \"fid\",
  C.FISHERY_SECTOR AS \"sector\",
  ISNULL(Year(COALESCE(C.BEST_DATE,C.START_DATE)),9999) AS \"year\",
  CONVERT(VARCHAR(10),COALESCE(C.BEST_DATE,C.START_DATE),20) AS \"date\",
  CAST(COALESCE(C.MAJOR_STAT_AREA_CODE,'00') AS NUMERIC) AS \"major\",
  CAST(COALESCE(C.MINOR_STAT_AREA_CODE,'00') AS NUMERIC) AS \"minor\",
  COALESCE(C.LOCALITY_CODE,0) AS \"locality\",
  CAST(COALESCE(C.DFO_STAT_AREA_CODE,'00') AS NUMERIC) AS \"dfoa\",
  COALESCE(C.DFO_STAT_SUBAREA_CODE,0) AS \"dfos\",
  (CASE
    WHEN C.MAJOR_STAT_AREA_CODE IN ('03') OR C.MINOR_STAT_AREA_CODE IN ('25') THEN '3C'
    WHEN C.MINOR_STAT_AREA_CODE IN ('26','27') THEN '3D'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('05') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       (C.LOCALITY_CODE IS NULL OR C.LOCALITY_CODE IN (0,1,2,3,4,5,7,8,9,10,13))) THEN '5AB'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('07','08') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       C.LOCALITY_CODE IN (6,11,12,14,15)) THEN '5CD'
    WHEN C.MINOR_STAT_AREA_CODE IN ('31','34') THEN '5ES'
    WHEN C.MINOR_STAT_AREA_CODE IN ('35') THEN '5EN'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('01') THEN 'SG'
    ELSE '' END) AS \"srfa\",
  COALESCE(C.BEST_DEPTH_FM,C.START_DEPTH_FM,0)*1.8288 AS \"depth\",
  SETS.LANDED + SETS.DISCARDED AS \"catch\",
  (CASE WHEN
    --(C.GEAR_SUBTYPE IN ('HARD BOTTOM TRAWL','SOFT BOTTOM TRAWL') OR   -- bottom --NO deprecated HARD and SOFT
    (C.GEAR_SUBTYPE IN ('BOTTOM TRAWL') OR   -- bottom
    (C.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
    C.TRIP_CATEGORY NOT IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
   THEN 1
   WHEN
    (C.GEAR_SUBTYPE IN ('MIDWATER TRAWL') OR   -- midwater
    (C.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
    C.TRIP_CATEGORY IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
   THEN 3 
   WHEN C.GEAR_SUBTYPE IN ('TRAP') THEN 2
   WHEN C.GEAR_SUBTYPE IN ('HOOK AND LINE') THEN 4
   WHEN C.GEAR_SUBTYPE IN ('LONGLINE') THEN 5
   ELSE 0 END) AS \"gear\"
INTO #FOSDEP
FROM 
  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
  INNER JOIN ( SELECT
    OC.TRIP_ID, OC.FISHING_EVENT_ID, OC.SPECIES_CODE,
    ISNULL(OC.LANDED_ROUND_KG,0) AS LANDED,
    COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (ISNULL(OC.SUBLEGAL_RELEASED_COUNT,0) + ISNULL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
      (ISNULL(OC.SUBLEGAL_LICED_COUNT,0) + ISNULL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
      (ISNULL(OC.SUBLEGAL_BAIT_COUNT,0) + ISNULL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT AS DISCARDED
    FROM
      GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH OC
      INNER JOIN @MEAN_WEIGHT FW ON -- FISH WEIGHTS FW
        OC.SPECIES_CODE = FW.SPECIES_CODE
    WHERE 
      OC.SPECIES_CODE  IN (@sppcode) AND
      OC.DATA_SOURCE_CODE IN (106) AND   -- flag for consideration (observerlogs only)
      --OC.DATA_SOURCE_CODE IN (105,106) AND   -- flag for consideration
      --OC.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND
      COALESCE(OC.MAJOR_STAT_AREA_CODE,'00') IN (@major) AND
      COALESCE(OC.BEST_DEPTH_FM,OC.START_DEPTH_FM,0) > 0 ) SETS ON
    C.TRIP_ID = SETS.TRIP_ID AND
    C.FISHING_EVENT_ID = SETS.FISHING_EVENT_ID AND
    C.SPECIES_CODE = SETS.SPECIES_CODE
WHERE (SETS.LANDED + SETS.DISCARDED) > 1

SELECT * 
--INTO #ALLCAT
FROM #PHTDEP
  UNION ALL SELECT * FROM #FOSDEP

--getData("pht_fdep.sql","PacHarvest",strSpp="396",major=5:7)
--qu("pht_fdep.sql",dbName="PacHarvest",strSpp="417")

