-- Query to get the fishing effort of all species. (RH 2017-01-16)
SET NOCOUNT ON

SELECT
  FE.OBFL_HAIL_IN_NO,
  'FDEPTH' = AVG(COALESCE(
    NULLIF(FE.Fishing_Depth,0), NULLIF(FE.OBFL_START_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_END_BOTTOM_DTH,0), NULLIF(FE.OBFL_MID_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_MIN_DTH,0), NULLIF(FE.OBFL_MAX_DTH,0), 0))
INTO #HailDepth
FROM 
  B3_Fishing_Events FE
GROUP BY 
  FE.OBFL_HAIL_IN_NO

SELECT --TOP 100
  'year'  = isNull(Year(COALESCE(E.Start_FE, E.OBFL_START_DT, E.OBFL_END_DT, T.OBFL_DEPARTURE_DT, T.OBFL_OFFLOAD_DT)),9999),
  'date'  = CONVERT(VARCHAR(10),COALESCE(E.Start_FE, E.OBFL_START_DT, E.OBFL_END_DT, T.OBFL_DEPARTURE_DT, T.OBFL_OFFLOAD_DT),20),
  'major' = ISNULL(E.OBFL_MAJOR_STAT_AREA_CDE, 0),
  'minor' = ISNULL(E.OBFL_MINOR_STAT_AREA_CDE, 0),
  'locality' = ISNULL(E.OBFL_LOCALITY_CDE, 0),
  'dfoa'  = ISNULL(E.OBFL_DFO_MGMT_AREA_CDE, 0),
  'dfos'  = ISNULL(E.OBFL_DFO_MGMT_SUBAREA_CDE, 0),
  'srfa'  = E.SRF_Major_Area1, 
  'depth' = COALESCE(E.Fishing_Depth, D.FDEPTH, 0),
  'effort' = ISNULL(E.Duration, 0),
  'gear'  = ISNULL(E.OBFL_GEAR_SUBTYPE_CDE,1)
INTO #PHTEFF
FROM 
  B3_Fishing_Events E
  LEFT OUTER JOIN #HailDepth D ON
    D.OBFL_HAIL_IN_NO = E.OBFL_HAIL_IN_NO
  LEFT OUTER JOIN B2_Trips T ON
    T.OBFL_HAIL_IN_NO = E.OBFL_HAIL_IN_NO
WHERE 
  COALESCE(E.Fishing_Depth, D.FDEPTH, 0) > 0 AND
  ISNULL(E.OBFL_MAJOR_STAT_AREA_CDE, 0) in (@major) AND
  E.OBFL_LOG_TYPE_CDE IN ('OBSERVRLOG') AND   -- flag for consideration (observerlogs only)
  ISNULL(E.Duration, 0) BETWEEN 1 AND 7200 -- > 0 & <= 5 days

-- SELECT TOP 100 * INTO #FOSEFF
--SELECT * INTO #FOSEFF
--FROM OPENQUERY(GFSH,'
SELECT --TOP 1000
  -- C.TRIP_ID, C.FISHING_EVENT_ID, C.SPECIES_CODE,
  ISNULL(YEAR(COALESCE(C.BEST_DATE,C.START_DATE)),9999) AS \"year\",
  CONVERT(VARCHAR(10),COALESCE(C.BEST_DATE,C.START_DATE),20) AS \"date\",
  CONVERT(INTEGER,COALESCE(C.MAJOR_STAT_AREA_CODE,'00')) AS \"major\",
  CONVERT(INTEGER,COALESCE(C.MINOR_STAT_AREA_CODE,'00')) AS \"minor\",
  --ISNULL(TO_NUMBER(TO_CHAR(COALESCE(C.BEST_DATE,C.START_DATE),'YYYY')),9999) AS \"year\",
  --TO_NUMBER(COALESCE(C.MAJOR_STAT_AREA_CODE,'00')) AS \"major\",
  --TO_NUMBER(COALESCE(C.MINOR_STAT_AREA_CODE,'00')) AS \"minor\",
  COALESCE(C.LOCALITY_CODE,0) AS \"locality\",
  CONVERT(INTEGER,COALESCE(C.DFO_STAT_AREA_CODE,'00')) AS \"dfoa\",
  --TO_NUMBER(COALESCE(C.DFO_STAT_AREA_CODE,'00')) AS \"dfoa\",
  COALESCE(C.DFO_STAT_SUBAREA_CODE,0) AS \"dfos\",
  (CASE
    WHEN C.MAJOR_STAT_AREA_CODE IN ('03') OR C.MINOR_STAT_AREA_CODE IN ('25') THEN '3C'
    WHEN C.MINOR_STAT_AREA_CODE IN ('26','27') THEN '3D'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('05') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       (C.LOCALITY_CODE IS NULL OR C.LOCALITY_CODE IN (0,1,2,3,4,5,7,8,9,10,13))) THEN '5AB'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('07','08') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       C.LOCALITY_CODE IN (6,11,12,14,15)) THEN '5CD'
    WHEN C.MINOR_STAT_AREA_CODE IN ('31','34') THEN '5ES'
    WHEN C.MINOR_STAT_AREA_CODE IN ('35') THEN '5EN'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('01') THEN 'SG'
    ELSE '' END) AS \"srfa\",
  AVG(COALESCE(C.BEST_DEPTH_FM,C.START_DEPTH_FM,0)*1.8288) AS \"depth\",
  AVG(CASE
    WHEN C.START_DATE IS NOT NULL AND C.END_DATE IS NOT NULL THEN
    DATEDIFF(minute,C.START_DATE,C.END_DATE) ELSE 0 END) AS \"effort\",   --effort in minutes
    --TO_NUMBER(C.END_DATE - C.START_DATE) * 24. * 60. ELSE 0 END) AS \"effort\",   --effort in minutes
  AVG(CASE WHEN
    (C.GEAR_SUBTYPE IN ('HARD BOTTOM TRAWL','SOFT BOTTOM TRAWL') OR   -- bottom
    (C.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
    C.TRIP_CATEGORY NOT IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
   THEN 1
   WHEN
    (C.GEAR_SUBTYPE IN ('MIDWATER TRAWL') OR   -- midwater
    (C.GEAR_SUBTYPE IN ('UNSPECIFIED') AND 
    C.TRIP_CATEGORY IN ('OPT A - HAKE QUOTA (GULF)','OPT A - HAKE QUOTA (SHORESIDE)','OPT A - HAKE QUOTA (JV)')))
   THEN 3 ELSE 0 END) AS \"gear\"
INTO #FOSEFF
FROM 
  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
WHERE 
  --C.DATA_SOURCE_CODE IN (105,106) AND   -- flag for consideration
  C.DATA_SOURCE_CODE IN (106) AND   -- flag for consideration (observerlogs only)
  C.FISHERY_SECTOR IN ('GROUNDFISH TRAWL') AND
  COALESCE(C.MAJOR_STAT_AREA_CODE,'00') IN (@major) AND
  COALESCE(C.BEST_DEPTH_FM,C.START_DEPTH_FM,0) > 0 AND 
  (CASE WHEN C.START_DATE IS NOT NULL AND C.END_DATE IS NOT NULL THEN
    DATEDIFF(minute,C.START_DATE,C.END_DATE) ELSE 0 END) BETWEEN 1 AND 7200 -- 5 days
GROUP 
  BY C.TRIP_ID, C.FISHING_EVENT_ID,
  ISNULL(YEAR(COALESCE(C.BEST_DATE,C.START_DATE)),9999),
  CONVERT(VARCHAR(10),COALESCE(C.BEST_DATE,C.START_DATE),20),
  CONVERT(INTEGER,COALESCE(C.MAJOR_STAT_AREA_CODE,'00')),
  CONVERT(INTEGER,COALESCE(C.MINOR_STAT_AREA_CODE,'00')),
  COALESCE(C.LOCALITY_CODE,0),
  CONVERT(INTEGER,COALESCE(C.DFO_STAT_AREA_CODE,'00')),
  COALESCE(C.DFO_STAT_SUBAREA_CODE,0),
  (CASE
    WHEN C.MAJOR_STAT_AREA_CODE IN ('03') OR C.MINOR_STAT_AREA_CODE IN ('25') THEN '3C'
    WHEN C.MINOR_STAT_AREA_CODE IN ('26','27') THEN '3D'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('05') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       (C.LOCALITY_CODE IS NULL OR C.LOCALITY_CODE IN (0,1,2,3,4,5,7,8,9,10,13))) THEN '5AB'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('07','08') OR (C.MINOR_STAT_AREA_CODE IN ('08') AND
       C.LOCALITY_CODE IN (6,11,12,14,15)) THEN '5CD'
    WHEN C.MINOR_STAT_AREA_CODE IN ('31','34') THEN '5ES'
    WHEN C.MINOR_STAT_AREA_CODE IN ('35') THEN '5EN'
    WHEN C.MAJOR_STAT_AREA_CODE IN ('01') THEN 'SG'
    ELSE '' END)
--')

SELECT * 
--INTO #ALLEFF
FROM #PHTEFF
  UNION ALL SELECT * FROM #FOSEFF

--getData("pht_effort.sql","PacHarvest",strSpp="396",major=5:7)
--qu("pht_effort.sql",dbName="PacHarvest",strSpp="417")


