-- Get depth data for a particular species
SET NOCOUNT ON

SELECT
  FE.OBFL_HAIL_IN_NO,
  'FDEPTH' = AVG(COALESCE(
    NULLIF(FE.Fishing_Depth,0), NULLIF(FE.OBFL_START_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_END_BOTTOM_DTH,0), NULLIF(FE.OBFL_MID_BOTTOM_DTH,0),
    NULLIF(FE.OBFL_MIN_DTH,0), NULLIF(FE.OBFL_MAX_DTH,0), 0))
INTO #HailDepth
FROM 
  B3_Fishing_Events FE
GROUP BY 
  FE.OBFL_HAIL_IN_NO

SELECT T1.OBFL_HAIL_IN_NO, V1.OBFL_VSL_CFV_NO
INTO #VessPHT
FROM
(SELECT * FROM
(SELECT
  VT.OBFL_VSL_CFV_NO,
  COUNT(VT.OBFL_YEAR) AS NYEARS,
  SUM(VT.NTRIPS) AS NTRIPS
FROM 
  (SELECT
    V.OBFL_VSL_CFV_NO,
    V.OBFL_YEAR,
    COUNT(V.OBFL_HAIL_IN_NO)AS NTRIPS
  FROM
    (SELECT
      T.OBFL_VSL_CFV_NO, 
      Year(COALESCE(T.OBFL_DEPARTURE_DT,T.OBFL_OFFLOAD_DT)) AS OBFL_YEAR,
      T.OBFL_HAIL_IN_NO
    FROM B2_Trips T
    GROUP BY
      T.OBFL_VSL_CFV_NO, 
      Year(COALESCE(T.OBFL_DEPARTURE_DT,T.OBFL_OFFLOAD_DT)), 
      T.OBFL_HAIL_IN_NO ) V
  GROUP BY
    V.OBFL_VSL_CFV_NO, 
    V.OBFL_YEAR) VT
WHERE VT.NTRIPS >=5
GROUP BY
  VT.OBFL_VSL_CFV_NO) VYT
WHERE VYT.NYEARS >= 3 ) V1
INNER JOIN B2_Trips T1 ON
V1.OBFL_VSL_CFV_NO = T1.OBFL_VSL_CFV_NO

SELECT --TOP 100
  'year'  = isNull(Year(COALESCE(E.Start_FE,E.OBFL_START_DT,E.OBFL_END_DT,OC.OFFLOAD_DATE)),9999),
  'major' = COALESCE(E.OBFL_MAJOR_STAT_AREA_CDE, OC.MAJOR_STAT_AREA, 0),
  'minor' = COALESCE(E.OBFL_MINOR_STAT_AREA_CDE, OC.MINOR_STAT_AREA, 0),
  'locality' = COALESCE(E.OBFL_LOCALITY_CDE, OC.LOCALITY_CDE, 0),
  'dfoa'  = COALESCE(E.OBFL_DFO_MGMT_AREA_CDE,OC.DFO_MGMT_AREA_CDE,0),
  'dfos'  = COALESCE(E.OBFL_DFO_MGMT_SUBAREA_CDE,OC.DFO_MGMT_SUBAREA_CDE,0),
  'srfa'  = E.SRF_Major_Area1, 
  'depth' = COALESCE(E.Fishing_Depth, D.FDEPTH, 0),
  'catch' = (MC.LANDED + MC.DISCARDED),
  'gear'  = COALESCE(E.OBFL_GEAR_SUBTYPE_CDE,1)
INTO #PHTDEP
FROM 
  #VessPHT VPHT INNER JOIN
  D_Merged_Catches MC ON 
    VPHT.OBFL_HAIL_IN_NO = MC.HAIL_IN_NO
  LEFT OUTER JOIN D_Official_Catch OC ON
    MC.HAIL_IN_NO = OC.HAIL_IN_NO AND 
    MC.SET_NO = OC.SET_NO AND 
    MC.SPECIES_CODE = OC.SPECIES_CODE
  LEFT OUTER JOIN B3_Fishing_Events E ON
    E.OBFL_HAIL_IN_NO = MC.HAIL_IN_NO AND 
    E.OBFL_SET_NO = MC.SET_NO
  LEFT OUTER JOIN #HailDepth D ON
    D.OBFL_HAIL_IN_NO = E.OBFL_HAIL_IN_NO
WHERE 
  COALESCE(E.Fishing_Depth, D.FDEPTH, 0) > 0 AND
  COALESCE(E.OBFL_MAJOR_STAT_AREA_CDE, OC.MAJOR_STAT_AREA, 0) in (@major) AND
  MC.SPECIES_CODE IN (@sppcode) AND
  (MC.LANDED + MC.DISCARDED) > 1

SELECT * INTO #FOSDEP
FROM OPENQUERY(GFSH,'
SELECT
  -- C.TRIP_ID, C.FISHING_EVENT_ID, C.SPECIES_CODE,
  NVL(TO_NUMBER(TO_CHAR(COALESCE(C.BEST_DATE,C.START_DATE),''YYYY'')),9999) AS \"year\",
  TO_NUMBER(COALESCE(C.MAJOR_STAT_AREA_CODE,''00'')) AS \"major\",
  TO_NUMBER(COALESCE(C.MINOR_STAT_AREA_CODE,''00'')) AS \"minor\",
  COALESCE(C.LOCALITY_CODE,0) AS \"locality\",
  TO_NUMBER(COALESCE(C.DFO_STAT_AREA_CODE,''00'')) AS \"dfoa\",
  COALESCE(C.DFO_STAT_SUBAREA_CODE,0) AS \"dfos\",
  (CASE
    WHEN C.MAJOR_STAT_AREA_CODE IN (''03'') OR C.MINOR_STAT_AREA_CODE IN (''25'') THEN ''3C''
    WHEN C.MINOR_STAT_AREA_CODE IN (''26'',''27'') THEN ''3D''
    WHEN C.MAJOR_STAT_AREA_CODE IN (''05'') OR (C.MINOR_STAT_AREA_CODE IN (''08'') AND
       (C.LOCALITY_CODE IS NULL OR C.LOCALITY_CODE IN (0,1,2,3,4,5,7,8,9,10,13))) THEN ''5AB''
    WHEN C.MAJOR_STAT_AREA_CODE IN (''07'',''08'') OR (C.MINOR_STAT_AREA_CODE IN (''08'') AND
       C.LOCALITY_CODE IN (6,11,12,14,15)) THEN ''5CD''
    WHEN C.MINOR_STAT_AREA_CODE IN (''31'',''34'') THEN ''5ES''
    WHEN C.MINOR_STAT_AREA_CODE IN (''35'') THEN ''5EN''
    WHEN C.MAJOR_STAT_AREA_CODE IN (''01'') THEN ''SG''
    ELSE '''' END) AS \"srfa\",
  COALESCE(C.BEST_DEPTH_FM,C.START_DEPTH_FM,0)*1.8288 AS \"depth\",
  SETS.LANDED + SETS.DISCARDED AS \"catch\",
  (CASE WHEN
    (C.GEAR_SUBTYPE IN (''HARD BOTTOM TRAWL'',''SOFT BOTTOM TRAWL'') OR   -- bottom
    (C.GEAR_SUBTYPE IN (''UNSPECIFIED'') AND 
    C.TRIP_CATEGORY NOT IN (''OPT A - HAKE QUOTA (GULF)'',''OPT A - HAKE QUOTA (SHORESIDE)'',''OPT A - HAKE QUOTA (JV)'')))
   THEN 1
   WHEN
    (C.GEAR_SUBTYPE IN (''MIDWATER TRAWL'') OR   -- midwater
    (C.GEAR_SUBTYPE IN (''UNSPECIFIED'') AND 
    C.TRIP_CATEGORY IN (''OPT A - HAKE QUOTA (GULF)'',''OPT A - HAKE QUOTA (SHORESIDE)'',''OPT A - HAKE QUOTA (JV)'')))
   THEN 3 ELSE 0 END) AS \"gear\"
FROM 
  GFFOS.GF_D_OFFICIAL_FE_CATCH C
  INNER JOIN ( SELECT
    OC.TRIP_ID, OC.FISHING_EVENT_ID, OC.SPECIES_CODE,
    NVL(OC.LANDED_ROUND_KG,0) AS LANDED,
    COALESCE(OC.TOTAL_RELEASED_ROUND_KG,
      (NVL(OC.SUBLEGAL_RELEASED_COUNT,0) + NVL(OC.LEGAL_RELEASED_COUNT,0)) * FW.MNWT, 0) +  -- released
      (NVL(OC.SUBLEGAL_LICED_COUNT,0) + NVL(OC.LEGAL_LICED_COUNT,0)) * FW.MNWT +            -- liced
      (NVL(OC.SUBLEGAL_BAIT_COUNT,0) + NVL(OC.LEGAL_BAIT_COUNT,0)) * FW.MNWT AS DISCARDED
    FROM
      GFFOS.GF_D_OFFICIAL_FE_CATCH OC
      INNER JOIN GFFOS.MEAN_SPECIES_WEIGHT_VW FW ON -- FISH WEIGHTS FW
        OC.SPECIES_CODE = FW.SPP
    WHERE 
      OC.SPECIES_CODE  IN (@~sppcode) AND
      OC.DATA_SOURCE_CODE IN (105,106) AND   -- flag for consideration
      OC.FISHERY_SECTOR IN (''GROUNDFISH TRAWL'') AND
      COALESCE(OC.MAJOR_STAT_AREA_CODE,''00'') IN (@major) AND
      COALESCE(OC.BEST_DEPTH_FM,OC.START_DEPTH_FM,0) > 0 ) SETS ON
    C.TRIP_ID = SETS.TRIP_ID AND
    C.FISHING_EVENT_ID = SETS.FISHING_EVENT_ID AND
    C.SPECIES_CODE = SETS.SPECIES_CODE
  INNER JOIN ( SELECT T2.TRIP_ID, V2.VESSEL_REGISTRATION_NUMBER FROM
  (SELECT * FROM
  (SELECT
    VT.VESSEL_REGISTRATION_NUMBER,
    COUNT(VT.OBFL_YEAR) AS NYEARS,
    SUM(VT.NTRIPS) AS NTRIPS
  FROM 
    (SELECT
      V.VESSEL_REGISTRATION_NUMBER,
      V.OBFL_YEAR,
      COUNT(V.TRIP_ID)AS NTRIPS
    FROM
      (SELECT
        T.VESSEL_REGISTRATION_NUMBER, 
        TO_NUMBER(TO_CHAR(COALESCE(T.TRIP_START_DATE,T.TRIP_END_DATE),''YYYY'')) AS OBFL_YEAR,
        T.TRIP_ID
      FROM GFFOS.GF_TRIP T
      GROUP BY
        T.VESSEL_REGISTRATION_NUMBER, 
        TO_NUMBER(TO_CHAR(COALESCE(T.TRIP_START_DATE,T.TRIP_END_DATE),''YYYY'')), 
        T.TRIP_ID ) V
    GROUP BY
      V.VESSEL_REGISTRATION_NUMBER, 
      V.OBFL_YEAR) VT
  WHERE VT.NTRIPS >=5
  GROUP BY
    VT.VESSEL_REGISTRATION_NUMBER) VYT
  WHERE VYT.NYEARS >= 3 ) V2
  INNER JOIN GFFOS.GF_TRIP T2 ON
  V2.VESSEL_REGISTRATION_NUMBER = T2.VESSEL_REGISTRATION_NUMBER ) VFOS ON
      VFOS.TRIP_ID = C.TRIP_ID
WHERE (SETS.LANDED + SETS.DISCARDED) > 1
')

SELECT * 
--INTO #ALLCAT
FROM #PHTDEP
  UNION ALL SELECT * FROM #FOSDEP


