SET NOCOUNT ON 

SELECT
  MC.HAIL_IN_NO, MC.SET_NO,
  CAST(SUM(ISNULL(MC.LANDED,0) + ISNULL(MC.DISCARDED,0)) AS INT) AS Tcat
  INTO #TCAT
  FROM 
    D_Merged_Catches MC
    INNER JOIN C_Species S ON
    MC.SPECIES_CODE = S.SPECIES_CDE
  WHERE 
    S.Fish = 1 OR
    S.Invertebrate =1 
  GROUP BY 
    MC.HAIL_IN_NO, MC.SET_NO 

SELECT *
  INTO #FCAT
  FROM #TCAT T
  WHERE T.Tcat > 0

SELECT
  E.OBFL_HAIL_IN_NO, E.OBFL_SET_NO, 
  COALESCE(-E.OBFL_START_LONGITUDE, -E.OBFL_END_LONGITUDE)AS X, 
  COALESCE(E.OBFL_START_LATITUDE, E.OBFL_END_LATITUDE) AS Y,
  E.Fishing_Depth AS depth
  INTO #Events 
  FROM 
    B3_Fishing_Events E 
    INNER JOIN #FCAT F ON
    E.OBFL_HAIL_IN_NO = F.HAIL_IN_NO AND
    E.OBFL_SET_NO = F.SET_NO
  WHERE 
    COALESCE(-E.OBFL_START_LONGITUDE, -E.OBFL_END_LONGITUDE) IS NOT NULL AND
    COALESCE(E.OBFL_START_LATITUDE, E.OBFL_END_LATITUDE) IS NOT NULL

SELECT --TOP 10
  V.X, V.Y,
  CAST(AVG(V.depth) AS INT) AS Z,
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t01code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Agnatha',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t02code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Chondrichthyes',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t03code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Clupeiformes',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t04code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Salmonidae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t05code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Osmeridae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t06code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Myctophidae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t07code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Gadidae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t08code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Macrouridae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t09code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Scombridae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t10code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Scorpaenidae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t11code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Hexagrammidae',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t12code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Pleuronectiformes',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@invcode) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Invertebrates'
  FROM 
    #Events V 
    INNER JOIN D_Merged_Catches MC ON
    V.OBFL_HAIL_IN_NO = MC.HAIL_IN_NO AND
    V.OBFL_SET_NO = MC.SET_NO 
--    INNER JOIN C_SPECIES S ON 
--    MC.SPECIES_CODE = S.SPECIES_CDE
--  WHERE 
--    S.Fish = 1 AND
--    S.Code3 IS NOT NULL
  GROUP BY
    V.X, V.Y

-- getData("pht_clara_groups.sql",strSpp="ZZZ")

