SET NOCOUNT ON

SELECT * FROM
(SELECT
  VT.OBFL_VSL_CFV_NO,
  COUNT(VT.OBFL_YEAR) AS NYEARS,
  SUM(VT.NTRIPS) AS NTRIPS
FROM 
  (SELECT
    V.OBFL_VSL_CFV_NO,
    V.OBFL_YEAR,
    COUNT(V.OBFL_HAIL_IN_NO)AS NTRIPS
  FROM
    (SELECT
      T.OBFL_VSL_CFV_NO, 
      Year(COALESCE(T.OBFL_DEPARTURE_DT,T.OBFL_OFFLOAD_DT)) AS OBFL_YEAR,
      T.OBFL_HAIL_IN_NO
    FROM B2_Trips T
    GROUP BY
      T.OBFL_VSL_CFV_NO, 
      Year(COALESCE(T.OBFL_DEPARTURE_DT,T.OBFL_OFFLOAD_DT)), 
      T.OBFL_HAIL_IN_NO ) V
  GROUP BY
    V.OBFL_VSL_CFV_NO, 
    V.OBFL_YEAR) VT
WHERE VT.NTRIPS >=5
GROUP BY
  VT.OBFL_VSL_CFV_NO) VYT
WHERE VYT.NYEARS >= 3
ORDER BY VYT.OBFL_VSL_CFV_NO

