SET NOCOUNT ON 

SELECT
  MC.HAIL_IN_NO, MC.SET_NO,
  CAST(SUM(ISNULL(MC.LANDED,0) + ISNULL(MC.DISCARDED,0)) AS INT) AS Tcat
  INTO #TCAT
  FROM 
    D_Merged_Catches MC
    INNER JOIN C_Species S ON
    MC.SPECIES_CODE = S.SPECIES_CDE
  WHERE 
    S.Fish = 1 OR
    S.Invertebrate =1 
  GROUP BY 
    MC.HAIL_IN_NO, MC.SET_NO 

SELECT *
  INTO #FCAT
  FROM #TCAT T
  WHERE T.Tcat > 0

SELECT
  E.OBFL_HAIL_IN_NO, E.OBFL_SET_NO, 
  COALESCE(-E.OBFL_START_LONGITUDE, -E.OBFL_END_LONGITUDE)AS X, 
  COALESCE(E.OBFL_START_LATITUDE, E.OBFL_END_LATITUDE) AS Y,
  E.Fishing_Depth AS depth
  INTO #Events 
  FROM 
    B3_Fishing_Events E 
    INNER JOIN #FCAT F ON
    E.OBFL_HAIL_IN_NO = F.HAIL_IN_NO AND
    E.OBFL_SET_NO = F.SET_NO
  WHERE 
    COALESCE(-E.OBFL_START_LONGITUDE, -E.OBFL_END_LONGITUDE) IS NOT NULL AND
    COALESCE(E.OBFL_START_LATITUDE, E.OBFL_END_LATITUDE) IS NOT NULL

SELECT --TOP 100
  V.X, V.Y,
  CAST(AVG(V.depth) AS INT) AS Z,
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN ('224','225') THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Hake',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN ('454','455') THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Sablefish',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t03code,@t04code,@t05code,@t09code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Pelagics',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@ssscode) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Sharks',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t10code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Rockfish',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t12code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Flatfish',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t11code) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Lingcod',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@t00code,@t06code,@t08code) AND MC.SPECIES_CODE NOT IN ('454','455') THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'OtherFish',
  CAST(SUM(CASE WHEN MC.SPECIES_CODE IN (@invcode) THEN (MC.LANDED + MC.DISCARDED) ELSE 0 END) AS INT) AS 'Inverts'
  FROM 
    #Events V 
    INNER JOIN D_Merged_Catches MC ON
    V.OBFL_HAIL_IN_NO = MC.HAIL_IN_NO AND
    V.OBFL_SET_NO = MC.SET_NO 
--    INNER JOIN C_SPECIES S ON 
--    MC.SPECIES_CODE = S.SPECIES_CDE
--  WHERE 
--    S.Fish = 1 AND
--    S.Code3 IS NOT NULL
  GROUP BY
    V.X, V.Y

-- getData("pht_clara_groups.sql",strSpp="ZZZ")

